import {requestGetPaymentBalance, requestListPracticeCard} from "../apis/web";

export const ReactQueryKeys = {
    CommentList: 'CommentList',
    kunDetail: 'kunDetail',
    notionPage: 'notionPage',
    userSession: 'userSession',
    userDetail: 'userDetail',
    userSubscribe: 'userSubscribe',
    useSeeDetail: 'useSeeDetail',
    AuthorProfile: 'AuthorProfile',
    getQueryGetSeriesDetail: 'getQueryGetSeriesDetail',
    getKunItemDetail: 'getKunItemDetail',
    getCommentItem: 'getCommentItem',
    getChildCommentItem: 'getChildCommentItem',
    getBlogList: 'getBlogList',
    getNotionBlog: 'getNotionBlog',
    getNotionTable: 'getNotionTable',
    getSeriesMember: 'getSeriesMember',
    getInfiniteCard: 'getInfiniteCard',
    getStarCollection: 'getStarCollection',
    getMyCreatedSeries: 'getMyCreatedSeries',
    getExcersice: 'getExcersice',
    getInfiniteMessage: 'getInfiniteMessage',
    getHeaderPin: 'getHeaderPinCard',
    requestListPracticeCard: 'requestListPracticeCard',
    requestGetPaymentBalance: 'requestGetPaymentBalance',
    getCardList: 'getCardList',
    getCardListSearchByEs: 'getCardListSearchByEs',
    requestGetPaymentHistory: 'requestGetPaymentHistory',
    getApiV1Search50Horse: 'getApiV1Search50Horse',
}