/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class A1Return {
    'doDummySend': boolean;
    'aliwwMsg'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "doDummySend",
            "baseName": "DoDummySend",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "aliwwMsg",
            "baseName": "AliwwMsg",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return A1Return.attributeTypeMap;
    }

    public constructor() {
    }
}

