/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatGroupByUser } from './ChatGroupByUser';
import { KunChatGroup } from './KunChatGroup';
import { HttpFile } from '../http/http';

export class ABGroup {
    'a'?: KunChatGroup;
    'b': ChatGroupByUser;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "a",
            "baseName": "a",
            "type": "KunChatGroup",
            "format": ""
        },
        {
            "name": "b",
            "baseName": "b",
            "type": "ChatGroupByUser",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ABGroup.attributeTypeMap;
    }

    public constructor() {
    }
}

