/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ASearchStore {
    'storecode': string;
    'storename': string;
    'distance': number;
    'cityName': string;
    'address': string;
    'lat': string;
    'lng': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "storecode",
            "baseName": "storecode",
            "type": "string",
            "format": ""
        },
        {
            "name": "storename",
            "baseName": "storename",
            "type": "string",
            "format": ""
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number",
            "format": "double"
        },
        {
            "name": "cityName",
            "baseName": "cityName",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "lat",
            "baseName": "lat",
            "type": "string",
            "format": ""
        },
        {
            "name": "lng",
            "baseName": "lng",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ASearchStore.attributeTypeMap;
    }

    public constructor() {
    }
}

