/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AttachItem {
    'id': number;
    'title': string;
    'tip': string;
    'sort': number;
    'merchantid': number;
    'attachgroupid': number;
    'type': number;
    'verification': number;
    'transform': number;
    'dropdownboxgroupid': number;
    'optiongroupid': number;
    'attachtype': number;
    'status': number;
    'createTime': number;
    'updateTime': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "tip",
            "baseName": "tip",
            "type": "string",
            "format": ""
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "number",
            "format": ""
        },
        {
            "name": "merchantid",
            "baseName": "merchantid",
            "type": "number",
            "format": ""
        },
        {
            "name": "attachgroupid",
            "baseName": "attachgroupid",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": ""
        },
        {
            "name": "verification",
            "baseName": "verification",
            "type": "number",
            "format": ""
        },
        {
            "name": "transform",
            "baseName": "transform",
            "type": "number",
            "format": ""
        },
        {
            "name": "dropdownboxgroupid",
            "baseName": "dropdownboxgroupid",
            "type": "number",
            "format": ""
        },
        {
            "name": "optiongroupid",
            "baseName": "optiongroupid",
            "type": "number",
            "format": ""
        },
        {
            "name": "attachtype",
            "baseName": "attachtype",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number",
            "format": ""
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AttachItem.attributeTypeMap;
    }

    public constructor() {
    }
}

