/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type EnumeratumConstantMsgFormat = "EnumMsgFormat_TEXT" | "EnumMsgFormat_IMAGE" | "EnumMsgFormat_AUDIO" | "EnumMsgFormat_FILE" | "EnumMsgFormat_COMMENT" ;
