/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantChargeType } from './ConstantChargeType';
import { ConstantSeriesType } from './ConstantSeriesType';
import { HashLong } from './HashLong';
import { HttpFile } from '../http/http';

export class HorseSeriesReturn {
    'id': HashLong;
    'title': string;
    'authorId': string;
    'seriesType': ConstantSeriesType;
    'latestVersion': number;
    'releaseVersion': number;
    'description'?: string;
    'learnPerDay'?: number;
    'categoryId'?: number;
    'subCategoryId'?: number;
    'coverImageName'?: string;
    'chargeType': ConstantChargeType;
    'releaseCreateAt'?: number;
    'createAt': number;
    'categoryName'?: string;
    'cardCount': number;
    'subscriptionCount': number;
    'isDelete': boolean;
    'visible': boolean;
    'groupId': string;
    'releaseUpdate'?: string;
    'link': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "HashLong",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorId",
            "baseName": "authorId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "seriesType",
            "baseName": "seriesType",
            "type": "ConstantSeriesType",
            "format": ""
        },
        {
            "name": "latestVersion",
            "baseName": "latestVersion",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "releaseVersion",
            "baseName": "releaseVersion",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "learnPerDay",
            "baseName": "learnPerDay",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "subCategoryId",
            "baseName": "subCategoryId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "coverImageName",
            "baseName": "coverImageName",
            "type": "string",
            "format": ""
        },
        {
            "name": "chargeType",
            "baseName": "chargeType",
            "type": "ConstantChargeType",
            "format": ""
        },
        {
            "name": "releaseCreateAt",
            "baseName": "releaseCreateAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "categoryName",
            "baseName": "categoryName",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardCount",
            "baseName": "cardCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "subscriptionCount",
            "baseName": "subscriptionCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "isDelete",
            "baseName": "isDelete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "releaseUpdate",
            "baseName": "releaseUpdate",
            "type": "string",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HorseSeriesReturn.attributeTypeMap;
    }

    public constructor() {
    }
}

