/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumeratumBenifitCardItem } from './EnumeratumBenifitCardItem';
import { EnumeratumValidStatus } from './EnumeratumValidStatus';
import { HttpFile } from '../http/http';

export class KunBenefitCard {
    'channelId': number;
    'userId': string;
    'card': EnumeratumBenifitCardItem;
    'status': EnumeratumValidStatus;
    'createAt': number;
    'updateAt': number;
    'expiredAt': number;
    'paymentList'?: Array<string>;
    'savedMoney': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "EnumeratumBenifitCardItem",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "EnumeratumValidStatus",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "expiredAt",
            "baseName": "expiredAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "paymentList",
            "baseName": "paymentList",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "savedMoney",
            "baseName": "savedMoney",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return KunBenefitCard.attributeTypeMap;
    }

    public constructor() {
    }
}

