/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantExerciseType } from './ConstantExerciseType';
import { ConstantSeriesType } from './ConstantSeriesType';
import { HttpFile } from '../http/http';

export class KunExercise {
    'channelId': number;
    'seriesId': string;
    'postId': string;
    'id': string;
    'exerciseType': ConstantExerciseType;
    'background'?: string;
    'title': string;
    'tips'?: string;
    'tags'?: Array<string>;
    'correct'?: Array<number>;
    'options'?: Array<string>;
    'answer'?: string;
    'editor'?: string;
    'editorName'?: string;
    'postTitle'?: string;
    'seriesName'?: string;
    'seriesType'?: ConstantSeriesType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "seriesId",
            "baseName": "seriesId",
            "type": "string",
            "format": ""
        },
        {
            "name": "postId",
            "baseName": "postId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "exerciseType",
            "baseName": "exerciseType",
            "type": "ConstantExerciseType",
            "format": ""
        },
        {
            "name": "background",
            "baseName": "background",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "tips",
            "baseName": "tips",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "correct",
            "baseName": "correct",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "answer",
            "baseName": "answer",
            "type": "string",
            "format": ""
        },
        {
            "name": "editor",
            "baseName": "editor",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "editorName",
            "baseName": "editorName",
            "type": "string",
            "format": ""
        },
        {
            "name": "postTitle",
            "baseName": "postTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "seriesName",
            "baseName": "seriesName",
            "type": "string",
            "format": ""
        },
        {
            "name": "seriesType",
            "baseName": "seriesType",
            "type": "ConstantSeriesType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KunExercise.attributeTypeMap;
    }

    public constructor() {
    }
}

