/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumeratumShandianOrderAllStatus } from './EnumeratumShandianOrderAllStatus';
import { HttpFile } from '../http/http';

export class KunSimpleOrder {
    'channelId': number;
    'userId': string;
    'orderId': string;
    'buyNum': number;
    'updateAt': number;
    'createAt': number;
    'title': string;
    'goodsid': string;
    'description'?: string;
    'paidMoney': number;
    'outOrderId': string;
    'orderStatus': EnumeratumShandianOrderAllStatus;
    'attachments'?: Array<string>;
    'phone'?: string;
    'address'?: string;
    'imageUrl'?: string;
    'receipt': string;
    'refundstatus': string;
    'refundreceipt'?: string;
    'statusDescription'?: string;
    'cardlists'?: Array<string>;
    'taobaoOrderId': string;
    'taobaoUserName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "buyNum",
            "baseName": "buyNum",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "goodsid",
            "baseName": "goodsid",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "paidMoney",
            "baseName": "paidMoney",
            "type": "number",
            "format": "double"
        },
        {
            "name": "outOrderId",
            "baseName": "outOrderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderStatus",
            "baseName": "orderStatus",
            "type": "EnumeratumShandianOrderAllStatus",
            "format": ""
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "receipt",
            "baseName": "receipt",
            "type": "string",
            "format": ""
        },
        {
            "name": "refundstatus",
            "baseName": "refundstatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "refundreceipt",
            "baseName": "refundreceipt",
            "type": "string",
            "format": ""
        },
        {
            "name": "statusDescription",
            "baseName": "statusDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardlists",
            "baseName": "cardlists",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taobaoOrderId",
            "baseName": "taobaoOrderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "taobaoUserName",
            "baseName": "taobaoUserName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KunSimpleOrder.attributeTypeMap;
    }

    public constructor() {
    }
}

