/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShandianOrder } from './ShandianOrder';
import { StarbuckPaidOrder } from './StarbuckPaidOrder';
import { HttpFile } from '../http/http';

export class KunShandianOrderTask {
    'data': StarbuckPaidOrder;
    'taskOpt'?: ShandianOrder;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "StarbuckPaidOrder",
            "format": ""
        },
        {
            "name": "taskOpt",
            "baseName": "taskOpt",
            "type": "ShandianOrder",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KunShandianOrderTask.attributeTypeMap;
    }

    public constructor() {
    }
}

