/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReqCreateConcern {
    'isUUID': boolean;
    'target': string;
    'isLinked': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isUUID",
            "baseName": "isUUID",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "string",
            "format": ""
        },
        {
            "name": "isLinked",
            "baseName": "isLinked",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqCreateConcern.attributeTypeMap;
    }

    public constructor() {
    }
}

