/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShandianItemCount } from './ShandianItemCount';
import { StarbuckStoreNameItem } from './StarbuckStoreNameItem';
import { HttpFile } from '../http/http';

export class ReqCreateShandianOrder {
    'paidOrderId'?: string;
    'location'?: StarbuckStoreNameItem;
    'items'?: Array<ShandianItemCount>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paidOrderId",
            "baseName": "paidOrderId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "StarbuckStoreNameItem",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ShandianItemCount>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqCreateShandianOrder.attributeTypeMap;
    }

    public constructor() {
    }
}

