/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReqGetExerciseItem {
    'exerciseId': string;
    'seriesId': string;
    'postId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "exerciseId",
            "baseName": "exerciseId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "seriesId",
            "baseName": "seriesId",
            "type": "string",
            "format": ""
        },
        {
            "name": "postId",
            "baseName": "postId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqGetExerciseItem.attributeTypeMap;
    }

    public constructor() {
    }
}

