/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantChargeType } from './ConstantChargeType';
import { HorseSeriesSortType } from './HorseSeriesSortType';
import { HttpFile } from '../http/http';

export class ReqQuerySeriesHorse {
    'chargeType'?: ConstantChargeType;
    'seriesSortType'?: HorseSeriesSortType;
    'categoryId'?: number;
    'subCategoryId'?: number;
    'pageMark'?: number;
    'pageSize'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chargeType",
            "baseName": "chargeType",
            "type": "ConstantChargeType",
            "format": ""
        },
        {
            "name": "seriesSortType",
            "baseName": "seriesSortType",
            "type": "HorseSeriesSortType",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "subCategoryId",
            "baseName": "subCategoryId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pageMark",
            "baseName": "pageMark",
            "type": "number",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqQuerySeriesHorse.attributeTypeMap;
    }

    public constructor() {
    }
}

