/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumTemperature } from './EnumTemperature';
import { EnumeratumBrand } from './EnumeratumBrand';
import { EnumeratumCupSize } from './EnumeratumCupSize';
import { EnumeratumStarbuckCat } from './EnumeratumStarbuckCat';
import { EnumeratumStarbuckItem } from './EnumeratumStarbuckItem';
import { EnumeratumTradeWay } from './EnumeratumTradeWay';
import { HttpFile } from '../http/http';

export class ShandianItem {
    'id': EnumeratumStarbuckItem;
    'name': string;
    'brandId': EnumeratumBrand;
    'categoryId': EnumeratumStarbuckCat;
    'price': number;
    'imageUrl'?: string;
    'originPrice': number;
    'size'?: Array<EnumeratumCupSize>;
    'temperature'?: Array<EnumTemperature>;
    'tradWay'?: Array<EnumeratumTradeWay>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "EnumeratumStarbuckItem",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandId",
            "baseName": "brandId",
            "type": "EnumeratumBrand",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "EnumeratumStarbuckCat",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "double"
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "originPrice",
            "baseName": "originPrice",
            "type": "number",
            "format": "double"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "Array<EnumeratumCupSize>",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "Array<EnumTemperature>",
            "format": ""
        },
        {
            "name": "tradWay",
            "baseName": "tradWay",
            "type": "Array<EnumeratumTradeWay>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ShandianItem.attributeTypeMap;
    }

    public constructor() {
    }
}

