/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumTemperature } from './EnumTemperature';
import { EnumeratumBrand } from './EnumeratumBrand';
import { EnumeratumCupSize } from './EnumeratumCupSize';
import { EnumeratumStarbuckItem } from './EnumeratumStarbuckItem';
import { HttpFile } from '../http/http';

export class ShandianItemCount {
    'brandEnum': EnumeratumBrand;
    'starbuckItem'?: EnumeratumStarbuckItem;
    'cupSize'?: EnumeratumCupSize;
    'count': number;
    'temperature'?: EnumTemperature;
    'kfcItem'?: EnumeratumStarbuckItem;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "brandEnum",
            "baseName": "brandEnum",
            "type": "EnumeratumBrand",
            "format": ""
        },
        {
            "name": "starbuckItem",
            "baseName": "starbuckItem",
            "type": "EnumeratumStarbuckItem",
            "format": ""
        },
        {
            "name": "cupSize",
            "baseName": "cupSize",
            "type": "EnumeratumCupSize",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "EnumTemperature",
            "format": ""
        },
        {
            "name": "kfcItem",
            "baseName": "kfcItem",
            "type": "EnumeratumStarbuckItem",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ShandianItemCount.attributeTypeMap;
    }

    public constructor() {
    }
}

