/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StarbuckStoreNameItem {
    'cityCode': number;
    'storeId': number;
    'storeName': string;
    'storeAddress': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cityCode",
            "baseName": "cityCode",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "storeId",
            "baseName": "storeId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "storeName",
            "baseName": "storeName",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeAddress",
            "baseName": "storeAddress",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StarbuckStoreNameItem.attributeTypeMap;
    }

    public constructor() {
    }
}

