/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumeratumBrand } from './EnumeratumBrand';
import { EnumeratumBuyCategory } from './EnumeratumBuyCategory';
import { EnumeratumStarbuckItem } from './EnumeratumStarbuckItem';
import { EnumeratumStarbuckOrderPaidStatus } from './EnumeratumStarbuckOrderPaidStatus';
import { HttpFile } from '../http/http';

export class StarbuckPaidOrder {
    'id': number;
    'orderId': string;
    'createAt': number;
    'taobaoId': string;
    'price': number;
    'userId': string;
    'userName': string;
    'phone': string;
    'kunOrderId'?: number;
    'status': EnumeratumStarbuckOrderPaidStatus;
    'title'?: string;
    'buyCategory': EnumeratumBuyCategory;
    'remark'?: string;
    'brand': EnumeratumBrand;
    'starbuckItem'?: EnumeratumStarbuckItem;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "taobaoId",
            "baseName": "taobaoId",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "double"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "kunOrderId",
            "baseName": "kunOrderId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "EnumeratumStarbuckOrderPaidStatus",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "buyCategory",
            "baseName": "buyCategory",
            "type": "EnumeratumBuyCategory",
            "format": ""
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string",
            "format": ""
        },
        {
            "name": "brand",
            "baseName": "brand",
            "type": "EnumeratumBrand",
            "format": ""
        },
        {
            "name": "starbuckItem",
            "baseName": "starbuckItem",
            "type": "EnumeratumStarbuckItem",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StarbuckPaidOrder.attributeTypeMap;
    }

    public constructor() {
    }
}

