/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VipShopGroupItem {
    'groupname': string;
    'groupaliasname': string;
    'groupid': number;
    'groupimgurl': string;
    'brandid': number;
    'brandname': string;
    'brandimgurl': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "groupname",
            "baseName": "groupname",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupaliasname",
            "baseName": "groupaliasname",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupid",
            "baseName": "groupid",
            "type": "number",
            "format": ""
        },
        {
            "name": "groupimgurl",
            "baseName": "groupimgurl",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandid",
            "baseName": "brandid",
            "type": "number",
            "format": ""
        },
        {
            "name": "brandname",
            "baseName": "brandname",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandimgurl",
            "baseName": "brandimgurl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VipShopGroupItem.attributeTypeMap;
    }

    public constructor() {
    }
}

