/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumeratumChatGroupType } from './EnumeratumChatGroupType';
import { HttpFile } from '../http/http';

export class ChatGroupByUser {
    'channelId': number;
    'groupType': EnumeratumChatGroupType;
    'userId': string;
    'groupId': string;
    'lastRead': string;
    'isStarter': boolean;
    'isActive': boolean;
    'groupName'?: string;
    'groupAvatar'?: string;
    'starterId'?: string;
    'starterName'?: string;
    'starterAvatar'?: string;
    'toId'?: string;
    'toName'?: string;
    'toAvatar'?: string;
    'chatBackground'?: string;
    'nickNameInGroup'?: string;
    'silence': boolean;
    'toRead'?: number;
    'updateAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "groupType",
            "baseName": "groupType",
            "type": "EnumeratumChatGroupType",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastRead",
            "baseName": "lastRead",
            "type": "string",
            "format": ""
        },
        {
            "name": "isStarter",
            "baseName": "isStarter",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "groupName",
            "baseName": "groupName",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupAvatar",
            "baseName": "groupAvatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "starterId",
            "baseName": "starterId",
            "type": "string",
            "format": ""
        },
        {
            "name": "starterName",
            "baseName": "starterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "starterAvatar",
            "baseName": "starterAvatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "toId",
            "baseName": "toId",
            "type": "string",
            "format": ""
        },
        {
            "name": "toName",
            "baseName": "toName",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAvatar",
            "baseName": "toAvatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "chatBackground",
            "baseName": "chatBackground",
            "type": "string",
            "format": ""
        },
        {
            "name": "nickNameInGroup",
            "baseName": "nickNameInGroup",
            "type": "string",
            "format": ""
        },
        {
            "name": "silence",
            "baseName": "silence",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "toRead",
            "baseName": "toRead",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatGroupByUser.attributeTypeMap;
    }

    public constructor() {
    }
}

