/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CommonSearchContent {
    'id': string;
    'title': string;
    'image'?: string;
    'rate'?: number;
    'isDelete': boolean;
    'isPublic': boolean;
    'tags'?: Array<string>;
    'images'?: Array<string>;
    'content'?: string;
    'description'?: string;
    'contentType'?: string;
    'updateAt'?: number;
    'createAt'?: number;
    'likeCount'?: number;
    'shareCount'?: number;
    'contentCount'?: number;
    'charge'?: number;
    'commentCount'?: number;
    'authorName'?: string;
    'authorDescription'?: string;
    'authorAvatar'?: string;
    'authorId'?: string;
    'categoryName'?: string;
    'categoryId'?: string;
    'text1'?: string;
    'double1'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": "double"
        },
        {
            "name": "isDelete",
            "baseName": "isDelete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPublic",
            "baseName": "isPublic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string",
            "format": ""
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "likeCount",
            "baseName": "likeCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "shareCount",
            "baseName": "shareCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "contentCount",
            "baseName": "contentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "charge",
            "baseName": "charge",
            "type": "number",
            "format": "double"
        },
        {
            "name": "commentCount",
            "baseName": "commentCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "authorName",
            "baseName": "authorName",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorDescription",
            "baseName": "authorDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorAvatar",
            "baseName": "authorAvatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorId",
            "baseName": "authorId",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryName",
            "baseName": "categoryName",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "string",
            "format": ""
        },
        {
            "name": "text1",
            "baseName": "text1",
            "type": "string",
            "format": ""
        },
        {
            "name": "double1",
            "baseName": "double1",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return CommonSearchContent.attributeTypeMap;
    }

    public constructor() {
    }
}

