/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumeratumChatRole } from './EnumeratumChatRole';
import { HttpFile } from '../http/http';

export class GetRtcToken {
    'channelName': string;
    'userId': string;
    'role': EnumeratumChatRole;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelName",
            "baseName": "channelName",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "EnumeratumChatRole",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetRtcToken.attributeTypeMap;
    }

    public constructor() {
    }
}

