/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReqAddDeliverMessage {
    'orderId': number;
    'remark': string;
    'remarkImage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string",
            "format": ""
        },
        {
            "name": "remarkImage",
            "baseName": "remarkImage",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqAddDeliverMessage.attributeTypeMap;
    }

    public constructor() {
    }
}

