/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HashLong } from './HashLong';
import { HttpFile } from '../http/http';

export class ReqCreateCardComment1 {
    'channelId': number;
    'seriesId': HashLong;
    'postId': HashLong;
    'content': string;
    'firstCommentId'?: string;
    'parentCommentId'?: string;
    'images'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "seriesId",
            "baseName": "seriesId",
            "type": "HashLong",
            "format": ""
        },
        {
            "name": "postId",
            "baseName": "postId",
            "type": "HashLong",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstCommentId",
            "baseName": "firstCommentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentCommentId",
            "baseName": "parentCommentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqCreateCardComment1.attributeTypeMap;
    }

    public constructor() {
    }
}

