/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HashLong } from './HashLong';
import { HttpFile } from '../http/http';

export class ReqGetAudioLog {
    'feedId': HashLong;
    'offset': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "feedId",
            "baseName": "feedId",
            "type": "HashLong",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ReqGetAudioLog.attributeTypeMap;
    }

    public constructor() {
    }
}

