/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReqGetHistoryMessage {
    'groupId': string;
    'timeUUID'?: string;
    'pageState'?: string;
    'pageSize'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeUUID",
            "baseName": "timeUUID",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageState",
            "baseName": "pageState",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqGetHistoryMessage.attributeTypeMap;
    }

    public constructor() {
    }
}

