/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantAppraiseType } from './ConstantAppraiseType';
import { HashLong } from './HashLong';
import { HttpFile } from '../http/http';

export class ReqUpdatePracticeAppraise {
    'seriesId': HashLong;
    'postId': HashLong;
    'practiceId': string;
    'appraiseType'?: ConstantAppraiseType;
    'practiceUserId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "seriesId",
            "baseName": "seriesId",
            "type": "HashLong",
            "format": ""
        },
        {
            "name": "postId",
            "baseName": "postId",
            "type": "HashLong",
            "format": ""
        },
        {
            "name": "practiceId",
            "baseName": "practiceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "appraiseType",
            "baseName": "appraiseType",
            "type": "ConstantAppraiseType",
            "format": ""
        },
        {
            "name": "practiceUserId",
            "baseName": "practiceUserId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqUpdatePracticeAppraise.attributeTypeMap;
    }

    public constructor() {
    }
}

