/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnumStarbuckBuyWay } from './EnumStarbuckBuyWay';
import { EnumeratumShandianOrderAllStatus } from './EnumeratumShandianOrderAllStatus';
import { EnumeratumStarItem } from './EnumeratumStarItem';
import { ShandianItemCount } from './ShandianItemCount';
import { HttpFile } from '../http/http';

export class ShandianOrder {
    'id': number;
    'channelId': number;
    'userId': string;
    'createAt': number;
    'location'?: string;
    'items'?: Array<ShandianItemCount>;
    'orderStatus': EnumeratumShandianOrderAllStatus;
    'remark'?: string;
    'remarkImage'?: string;
    'buyWay': EnumStarbuckBuyWay;
    'item'?: EnumeratumStarItem;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ShandianItemCount>",
            "format": ""
        },
        {
            "name": "orderStatus",
            "baseName": "orderStatus",
            "type": "EnumeratumShandianOrderAllStatus",
            "format": ""
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string",
            "format": ""
        },
        {
            "name": "remarkImage",
            "baseName": "remarkImage",
            "type": "string",
            "format": ""
        },
        {
            "name": "buyWay",
            "baseName": "buyWay",
            "type": "EnumStarbuckBuyWay",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "EnumeratumStarItem",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ShandianOrder.attributeTypeMap;
    }

    public constructor() {
    }
}

