/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StarbuckAddress } from './StarbuckAddress';
import { StarbuckLocation } from './StarbuckLocation';
import { StarbuckOpenClose } from './StarbuckOpenClose';
import { HttpFile } from '../http/http';

export class StarbuckStore {
    'name': string;
    'address': StarbuckAddress;
    'today': StarbuckOpenClose;
    'coordinates': StarbuckLocation;
    'storeNumber': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "StarbuckAddress",
            "format": ""
        },
        {
            "name": "today",
            "baseName": "today",
            "type": "StarbuckOpenClose",
            "format": ""
        },
        {
            "name": "coordinates",
            "baseName": "coordinates",
            "type": "StarbuckLocation",
            "format": ""
        },
        {
            "name": "storeNumber",
            "baseName": "storeNumber",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StarbuckStore.attributeTypeMap;
    }

    public constructor() {
    }
}

