// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const bkInhabitant = 'bk';

export type bk = typeof bkInhabitant;

export function isbk(v: any): v is bk {
  return bkInhabitant == v;
}
