// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const blockInhabitant = 'block';

export type block = typeof blockInhabitant;

export function isblock(v: any): v is block {
  return blockInhabitant == v;
}
