// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { SymbolEnum, isSymbolEnum } from './SymbolEnum';

export interface BlockSymbol {
  symbolType: SymbolEnum;
}

export function isBlockSymbol(v: any): v is BlockSymbol {
  return (
    (v['symbolType'] && isSymbolEnum(v['symbolType']))
  );
}
