// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const commandSellInhabitant = 'commandSell';

export type commandSell = typeof commandSellInhabitant;

export function iscommandSell(v: any): v is commandSell {
  return commandSellInhabitant == v;
}
