// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface ConfirmationContractObject {
}

export function isConfirmationContractObject(v: any): v is ConfirmationContractObject {
  return true;
}
