// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { SymbolEnum, isSymbolEnum } from './SymbolEnum';

export interface ConvertibleSymbol {
  symbolType: SymbolEnum;
}

export function isConvertibleSymbol(v: any): v is ConvertibleSymbol {
  return (
    (v['symbolType'] && isSymbolEnum(v['symbolType']))
  );
}
