// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const convertibleInhabitant = 'convertible';

export type convertible = typeof convertibleInhabitant;

export function isconvertible(v: any): v is convertible {
  return convertibleInhabitant == v;
}
