// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const DateFormatInhabitant = 'DateFormat';

export type DateFormat = typeof DateFormatInhabitant;

export function isDateFormat(v: any): v is DateFormat {
  return DateFormatInhabitant == v;
}
