// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const emptyInhabitant = 'empty';

export type empty = typeof emptyInhabitant;

export function isempty(v: any): v is empty {
  return emptyInhabitant == v;
}
