// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { EnumeratumOfferChargeType_CUSTOM, isEnumeratumOfferChargeType_CUSTOM } from './EnumeratumOfferChargeType_CUSTOM';
import { EnumeratumOfferChargeType_DURATION, isEnumeratumOfferChargeType_DURATION } from './EnumeratumOfferChargeType_DURATION';
import { EnumeratumOfferChargeType_TIMES, isEnumeratumOfferChargeType_TIMES } from './EnumeratumOfferChargeType_TIMES';

export type EnumeratumOfferChargeType = EnumeratumOfferChargeType_CUSTOM | EnumeratumOfferChargeType_DURATION | EnumeratumOfferChargeType_TIMES;

export function isEnumeratumOfferChargeType(v: any): v is EnumeratumOfferChargeType {
  return (
    isEnumeratumOfferChargeType_CUSTOM(v) ||
    isEnumeratumOfferChargeType_DURATION(v) ||
    isEnumeratumOfferChargeType_TIMES(v)
  );
}
