// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const EnumeratumOfferChargeType_CUSTOMInhabitant = 'EnumeratumOfferChargeType_CUSTOM';

export type EnumeratumOfferChargeType_CUSTOM = typeof EnumeratumOfferChargeType_CUSTOMInhabitant;

export function isEnumeratumOfferChargeType_CUSTOM(v: any): v is EnumeratumOfferChargeType_CUSTOM {
  return EnumeratumOfferChargeType_CUSTOMInhabitant == v;
}
