// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface FundDateList {
  date: Date;
  price: number;
  change_pct: number;
}

export function isFundDateList(v: any): v is FundDateList {
  return (
    ((typeof v['change_pct']) === 'number') &&
    ((typeof v['price']) === 'number') &&
    (v['date'] && (v['date'] instanceof Date))
  );
}
