// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const HX50Inhabitant = "华夏上证50ETF期权";

export type HX50 = typeof HX50Inhabitant;

export function isHX50(v: any): v is HX50 {
  return HX50Inhabitant == v;
}
