// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';

export interface IndexDailyPriceJodata {
  date: DateTime;
  close: number;
  volume: number;
  open: number;
  high: number;
  low: number;
}

export function isIndexDailyPriceJodata(v: any): v is IndexDailyPriceJodata {
  return (
    ((typeof v['low']) === 'number') &&
    ((typeof v['high']) === 'number') &&
    ((typeof v['open']) === 'number') &&
    ((typeof v['volume']) === 'number') &&
    ((typeof v['close']) === 'number') &&
    (v['date'] && isDateTime(v['date']))
  );
}
