// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { SymbolEnum, isSymbolEnum } from './SymbolEnum';

export interface IndexSymbol {
  symbolType: SymbolEnum;
}

export function isIndexSymbol(v: any): v is IndexSymbol {
  return (
    (v['symbolType'] && isSymbolEnum(v['symbolType']))
  );
}
