// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface IndexContain {
  code: string;
  name: string;
  date: Date;
}

export function isIndexContain(v: any): v is IndexContain {
  return (
    (v['date'] && (v['date'] instanceof Date)) &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['code']) === 'string')
  );
}
