// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';

export interface ItemPrice {
  date: DateTime;
  price: number;
}

export function isItemPrice(v: any): v is ItemPrice {
  return (
    ((typeof v['price']) === 'number') &&
    (v['date'] && isDateTime(v['date']))
  );
}
