// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const jijinInhabitant = 'jijin';

export type jijin = typeof jijinInhabitant;

export function isjijin(v: any): v is jijin {
  return jijinInhabitant == v;
}
