// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { SymbolEnum, isSymbolEnum } from './SymbolEnum';

export interface JiJinSymbol {
  symbolType: SymbolEnum;
}

export function isJiJinSymbol(v: any): v is JiJinSymbol {
  return (
    (v['symbolType'] && isSymbolEnum(v['symbolType']))
  );
}
