// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface KeyValueOptionValue {
  date: string;
  up: number;
  down: number;
  zhangting: number;
  dieting: number;
  rate: string;
}

export function isKeyValueOptionValue(v: any): v is KeyValueOptionValue {
  return (
    ((typeof v['rate']) === 'string') &&
    ((typeof v['dieting']) === 'number') &&
    ((typeof v['zhangting']) === 'number') &&
    ((typeof v['down']) === 'number') &&
    ((typeof v['up']) === 'number') &&
    ((typeof v['date']) === 'string')
  );
}
