// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const LqHtmlInhabitant = 'LqHtml';

export type LqHtml = typeof LqHtmlInhabitant;

export function isLqHtml(v: any): v is LqHtml {
  return LqHtmlInhabitant == v;
}
