// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface LStockItemContinueDate {
  date: Date;
  count: number;
}

export function isLStockItemContinueDate(v: any): v is LStockItemContinueDate {
  return (
    ((typeof v['count']) === 'number') &&
    (v['date'] && (v['date'] instanceof Date))
  );
}
