// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { BlockSymbol, isBlockSymbol } from './BlockSymbol';
import { ConvertibleSymbol, isConvertibleSymbol } from './ConvertibleSymbol';
import { HkSymbol, isHkSymbol } from './HkSymbol';
import { IndexSymbol, isIndexSymbol } from './IndexSymbol';
import { JiJinSymbol, isJiJinSymbol } from './JiJinSymbol';
import { OptionSymbol, isOptionSymbol } from './OptionSymbol';
import { StockSymbol, isStockSymbol } from './StockSymbol';
import { SwIndexSymbol, isSwIndexSymbol } from './SwIndexSymbol';
import { UsSymbol, isUsSymbol } from './UsSymbol';

export type LSymbol = BlockSymbol | ConvertibleSymbol | HkSymbol | IndexSymbol | JiJinSymbol | OptionSymbol | StockSymbol | SwIndexSymbol | UsSymbol;

export function isLSymbol(v: any): v is LSymbol {
  return (
    isBlockSymbol(v) ||
    isConvertibleSymbol(v) ||
    isHkSymbol(v) ||
    isIndexSymbol(v) ||
    isJiJinSymbol(v) ||
    isOptionSymbol(v) ||
    isStockSymbol(v) ||
    isSwIndexSymbol(v) ||
    isUsSymbol(v)
  );
}
