// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const marketInhabitant = 'market';

export type market = typeof marketInhabitant;

export function ismarket(v: any): v is market {
  return marketInhabitant == v;
}
