// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const MovingAverageInhabitant = 'MovingAverage';

export type MovingAverage = typeof MovingAverageInhabitant;

export function isMovingAverage(v: any): v is MovingAverage {
  return MovingAverageInhabitant == v;
}
