// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const ObjectConvertInhabitant = 'ObjectConvert';

export type ObjectConvert = typeof ObjectConvertInhabitant;

export function isObjectConvert(v: any): v is ObjectConvert {
  return ObjectConvertInhabitant == v;
}
