// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { CALL, isCALL } from './CALL';
import { PUT, isPUT } from './PUT';

export type OptionDirection = CALL | PUT;

export function isOptionDirection(v: any): v is OptionDirection {
  return (
    isCALL(v) ||
    isPUT(v)
  );
}
