// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { HT300, isHT300 } from './HT300';
import { HX50, isHX50 } from './HX50';

export type OptionProductName = HT300 | HX50;

export function isOptionProductName(v: any): v is OptionProductName {
  return (
    isHT300(v) ||
    isHX50(v)
  );
}
