// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { commandBuy, iscommandBuy } from './commandBuy';
import { commandSell, iscommandSell } from './commandSell';

export type OrderCommand = commandBuy | commandSell;

export function isOrderCommand(v: any): v is OrderCommand {
  return (
    iscommandBuy(v) ||
    iscommandSell(v)
  );
}
