// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface PanMingChaoDieItem {
  chaodie: number;
  date: string;
}

export function isPanMingChaoDieItem(v: any): v is PanMingChaoDieItem {
  return (
    ((typeof v['date']) === 'string') &&
    ((typeof v['chaodie']) === 'number')
  );
}
