// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface PanMingChaoDieItem1 {
  chaodie: number;
  date: Date;
}

export function isPanMingChaoDieItem1(v: any): v is PanMingChaoDieItem1 {
  return (
    (v['date'] && (v['date'] instanceof Date)) &&
    ((typeof v['chaodie']) === 'number')
  );
}
