// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface PanMingChaoDieItem2 {
  value: number;
  date: Date;
}

export function isPanMingChaoDieItem2(v: any): v is PanMingChaoDieItem2 {
  return (
    (v['date'] && (v['date'] instanceof Date)) &&
    ((typeof v['value']) === 'number')
  );
}
