// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const PUTInhabitant = "PUT";

export type PUT = typeof PUTInhabitant;

export function isPUT(v: any): v is PUT {
  return PUTInhabitant == v;
}
