// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface Qiangshigu {
  名称: string;
  代码: string;
  所属行业: string;
}

export function isQiangshigu(v: any): v is Qiangshigu {
  return (
    ((typeof v['所属行业']) === 'string') &&
    ((typeof v['代码']) === 'string') &&
    ((typeof v['名称']) === 'string')
  );
}
