// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface ReqSellContract {
  contractId: string;
}

export function isReqSellContract(v: any): v is ReqSellContract {
  return (
    ((typeof v['contractId']) === 'string')
  );
}
