// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface ReqSellStock {
  contractId: string;
  stockSymbol: string;
}

export function isReqSellStock(v: any): v is ReqSellStock {
  return (
    ((typeof v['stockSymbol']) === 'string') &&
    ((typeof v['contractId']) === 'string')
  );
}
