// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const restrictInhabitant = 'restrict';

export type restrict = typeof restrictInhabitant;

export function isrestrict(v: any): v is restrict {
  return restrictInhabitant == v;
}
