// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { IndexDailyPriceJodata, isIndexDailyPriceJodata } from './IndexDailyPriceJodata';

export interface RetIndexPrice {
  records: ReadonlyArray<IndexDailyPriceJodata>;
}

export function isRetIndexPrice(v: any): v is RetIndexPrice {
  return (
    (Array.isArray(v['records']) && v['records'].every(elmt => elmt && isIndexDailyPriceJodata(elmt)))
  );
}
