// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { WeatherStation1, isWeatherStation1 } from './WeatherStation1';

export interface RetStock {
  records: ReadonlyArray<WeatherStation1>;
}

export function isRetStock(v: any): v is RetStock {
  return (
    (Array.isArray(v['records']) && v['records'].every(elmt => elmt && isWeatherStation1(elmt)))
  );
}
