// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { StockChaoDieJoda, isStockChaoDieJoda } from './StockChaoDieJoda';

export interface RetStockChaoDie {
  records: ReadonlyArray<StockChaoDieJoda>;
}

export function isRetStockChaoDie(v: any): v is RetStockChaoDie {
  return (
    (Array.isArray(v['records']) && v['records'].every(elmt => elmt && isStockChaoDieJoda(elmt)))
  );
}
