// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const stockInhabitant = 'stock';

export type stock = typeof stockInhabitant;

export function isstock(v: any): v is stock {
  return stockInhabitant == v;
}
