// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface StockPrice {
  open: number;
  close: number;
  high: number;
  low: number;
}

export function isStockPrice(v: any): v is StockPrice {
  return (
    ((typeof v['low']) === 'number') &&
    ((typeof v['high']) === 'number') &&
    ((typeof v['close']) === 'number') &&
    ((typeof v['open']) === 'number')
  );
}
