// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface StockSellNote {
  name: string;
  important: boolean;
}

export function isStockSellNote(v: any): v is StockSellNote {
  return (
    ((typeof v['important']) === 'boolean') &&
    ((typeof v['name']) === 'string')
  );
}
