// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface StockCodePrice {
  code: string;
  open: number;
  close: number;
  high: number;
  low: number;
}

export function isStockCodePrice(v: any): v is StockCodePrice {
  return (
    ((typeof v['low']) === 'number') &&
    ((typeof v['high']) === 'number') &&
    ((typeof v['close']) === 'number') &&
    ((typeof v['open']) === 'number') &&
    ((typeof v['code']) === 'string')
  );
}
