// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';

export interface StockChaoDieJoda {
  date: DateTime;
  chaodie: number;
}

export function isStockChaoDieJoda(v: any): v is StockChaoDieJoda {
  return (
    ((typeof v['chaodie']) === 'number') &&
    (v['date'] && isDateTime(v['date']))
  );
}
