// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { OrderCommand, isOrderCommand } from './OrderCommand';
import { OrderPriceType, isOrderPriceType } from './OrderPriceType';
import { StockSymbol, isStockSymbol } from './StockSymbol';

export interface StockOrder {
  symbol: StockSymbol;
  direction: OrderCommand;
  priceType?: OrderPriceType;
  amountOpt?: number;
  priceOpt?: number;
}

export function isStockOrder(v: any): v is StockOrder {
  return (
    (!v['priceOpt'] || ((typeof v['priceOpt']) === 'number')) &&
    (!v['amountOpt'] || ((typeof v['amountOpt']) === 'number')) &&
    (!v['priceType'] || (v['priceType'] && isOrderPriceType(v['priceType']))) &&
    (v['direction'] && isOrderCommand(v['direction'])) &&
    (v['symbol'] && isStockSymbol(v['symbol']))
  );
}
