// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { SymbolEnum, isSymbolEnum } from './SymbolEnum';

export interface SwIndexSymbol {
  symbolType: SymbolEnum;
}

export function isSwIndexSymbol(v: any): v is SwIndexSymbol {
  return (
    (v['symbolType'] && isSymbolEnum(v['symbolType']))
  );
}
