// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface SWIndexItem {
  index_code: string;
  index_name: string;
  date: Date;
  open: number;
  high: number;
  low: number;
  close: number;
  vol: number;
  amount: number;
  change_pct: number;
}

export function isSWIndexItem(v: any): v is SWIndexItem {
  return (
    ((typeof v['change_pct']) === 'number') &&
    ((typeof v['amount']) === 'number') &&
    ((typeof v['vol']) === 'number') &&
    ((typeof v['close']) === 'number') &&
    ((typeof v['low']) === 'number') &&
    ((typeof v['high']) === 'number') &&
    ((typeof v['open']) === 'number') &&
    (v['date'] && (v['date'] instanceof Date)) &&
    ((typeof v['index_name']) === 'string') &&
    ((typeof v['index_code']) === 'string')
  );
}
