// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const ukInhabitant = 'uk';

export type uk = typeof ukInhabitant;

export function isuk(v: any): v is uk {
  return ukInhabitant == v;
}
