// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { SymbolEnum, isSymbolEnum } from './SymbolEnum';

export interface UsSymbol {
  symbolType: SymbolEnum;
}

export function isUsSymbol(v: any): v is UsSymbol {
  return (
    (v['symbolType'] && isSymbolEnum(v['symbolType']))
  );
}
