// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export interface VIxItem {
  vix: number;
  date: string;
  skew: number;
}

export function isVIxItem(v: any): v is VIxItem {
  return (
    ((typeof v['skew']) === 'number') &&
    ((typeof v['date']) === 'string') &&
    ((typeof v['vix']) === 'number')
  );
}
