// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';

export interface WeatherStation1 {
  date: DateTime;
  open: number;
  close: number;
  high: number;
  low: number;
  volume: number;
  turnover: number;
  outstanding_share: number;
}

export function isWeatherStation1(v: any): v is WeatherStation1 {
  return (
    ((typeof v['outstanding_share']) === 'number') &&
    ((typeof v['turnover']) === 'number') &&
    ((typeof v['volume']) === 'number') &&
    ((typeof v['low']) === 'number') &&
    ((typeof v['high']) === 'number') &&
    ((typeof v['close']) === 'number') &&
    ((typeof v['open']) === 'number') &&
    (v['date'] && isDateTime(v['date']))
  );
}
