import {ConstNotionPage} from "../app/kun-config";

export const CONSTANT_ROUTES = {
    CreateSeries : '/live/create-series',
    Home : '/live/home',
    Discover : '/live/discover',
    Blog : '/live/blog/:name',
    Help : `/live/p/${ConstNotionPage.OneONePage}`,
    Setting : '/live/setting',
    NoticeSetting : '/live/notice-setting',
    ExerciseList : '/live/list/exercise',
    Contacts : '/live/setting-contact',
    Author : '/live/user/:userId',
    Tribe : '/live/tribe',
    SeriesHome : '/live/s/:id',
    SeriesSetting : '/live/series-setting/:id',
    Wallet : '/live/wallet', // wallet
    KunItemPage : '/live/k/:symbol/:id',
    About : '/live/about',
    BaiduYunDownload : '/live/baiduyun-download',
    Order : '/live/order',
    CommentItem : '/live/comment/:channelId/:id',
    PostCommentItem : '/live/discuss/:channelId/:postId/:commentId',
    CurrentLearning : '/live/current',
    MessageSuccess : '/live/success',
    Chat : '/live/chat',
    Tag : '/live/t/:tag',
    Direct : '/live/direct/:id',

    PracticePage : '/live/practice/:seriesId/:postId/:exerciseId',

    ChatRoom : '/live/chat-room/:roomId',

    KunPage : '/live/kun/:name',
    Notion : '/live/p/:name',
    NPage: '/:name',
    CollectionAll : '/live/collection/:channelId/:userId',
    Collection : '/live/collection/:channelId/:userId/:msgType',
    SymbolCreate : '/live/symbol/create',
    ArticleV2 : '/live/article2',
    Events : '/live/events',
    IndexEvents : '/live/indexEvents',
    Login : '/live/login',
    Article : '/live/article/:seriesId/:id',
    MySeries : '/live/series',
    InternalError : '/live/internal-error',
    // InternalError : '/live/503',
    Write : '/live/write',
    EditPost : '/live/edit',
    Test : '/live/test',
    Admin : '/live/admin',
    MySubscription : '/live/subscription',
    SeriesDetail: '/live/series-detail',
    NotFound: "/live/404",
    Search: '/live/search',
    ConcernMembers: '/live/concern-members',
    Timeline: '/live/timeline',
}