/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface A1Return
 */
export interface A1Return {
    /**
     * 
     * @type {boolean}
     * @memberof A1Return
     */
    doDummySend: boolean;
    /**
     * 
     * @type {string}
     * @memberof A1Return
     */
    aliwwMsg?: string;
}

export function A1ReturnFromJSON(json: any): A1Return {
    return A1ReturnFromJSONTyped(json, false);
}

export function A1ReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): A1Return {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doDummySend': json['DoDummySend'],
        'aliwwMsg': !exists(json, 'AliwwMsg') ? undefined : json['AliwwMsg'],
    };
}

export function A1ReturnToJSON(value?: A1Return | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DoDummySend': value.doDummySend,
        'AliwwMsg': value.aliwwMsg,
    };
}

