/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddStarbuckGrouponTicket
 */
export interface AddStarbuckGrouponTicket {
    /**
     * 
     * @type {string}
     * @memberof AddStarbuckGrouponTicket
     */
    taobaoId: string;
    /**
     * 
     * @type {number}
     * @memberof AddStarbuckGrouponTicket
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof AddStarbuckGrouponTicket
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof AddStarbuckGrouponTicket
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof AddStarbuckGrouponTicket
     */
    phone: string;
}

export function AddStarbuckGrouponTicketFromJSON(json: any): AddStarbuckGrouponTicket {
    return AddStarbuckGrouponTicketFromJSONTyped(json, false);
}

export function AddStarbuckGrouponTicketFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddStarbuckGrouponTicket {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taobaoId': json['taobaoId'],
        'price': json['price'],
        'userId': json['userId'],
        'userName': json['userName'],
        'phone': json['phone'],
    };
}

export function AddStarbuckGrouponTicketToJSON(value?: AddStarbuckGrouponTicket | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taobaoId': value.taobaoId,
        'price': value.price,
        'userId': value.userId,
        'userName': value.userName,
        'phone': value.phone,
    };
}

