/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ConstantMSG {
    NUMBER_3000 = 3000,
    NUMBER_2001 = 2001,
    NUMBER_1001 = 1001,
    NUMBER_3001 = 3001,
    NUMBER_4000 = 4000,
    NUMBER_6001 = 6001,
    NUMBER_8001 = 8001,
    NUMBER_5001 = 5001
}

export function ConstantMSGFromJSON(json: any): ConstantMSG {
    return ConstantMSGFromJSONTyped(json, false);
}

export function ConstantMSGFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstantMSG {
    return json as ConstantMSG;
}

export function ConstantMSGToJSON(value?: ConstantMSG | null): any {
    return value as any;
}

