/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ConstantChargeType {
    Free = 'FREE',
    Charge = 'CHARGE'
}

export function ConstantChargeTypeFromJSON(json: any): ConstantChargeType {
    return ConstantChargeTypeFromJSONTyped(json, false);
}

export function ConstantChargeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstantChargeType {
    return json as ConstantChargeType;
}

export function ConstantChargeTypeToJSON(value?: ConstantChargeType | null): any {
    return value as any;
}

