/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ConstantPaymentStatus {
    Start = 'START',
    Success = 'SUCCESS',
    Fail = 'FAIL'
}

export function ConstantPaymentStatusFromJSON(json: any): ConstantPaymentStatus {
    return ConstantPaymentStatusFromJSONTyped(json, false);
}

export function ConstantPaymentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstantPaymentStatus {
    return json as ConstantPaymentStatus;
}

export function ConstantPaymentStatusToJSON(value?: ConstantPaymentStatus | null): any {
    return value as any;
}

