/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumeratumChatGroupType {
    Comment = 'COMMENT',
    System = 'SYSTEM',
    Like = 'LIKE',
    HorseSeries = 'HORSE_SERIES',
    PrivateChat = 'PRIVATE_CHAT'
}

export function EnumeratumChatGroupTypeFromJSON(json: any): EnumeratumChatGroupType {
    return EnumeratumChatGroupTypeFromJSONTyped(json, false);
}

export function EnumeratumChatGroupTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumChatGroupType {
    return json as EnumeratumChatGroupType;
}

export function EnumeratumChatGroupTypeToJSON(value?: EnumeratumChatGroupType | null): any {
    return value as any;
}

