/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumeratumConstantMsgFormat {
    Text = 'EnumMsgFormat_TEXT',
    Image = 'EnumMsgFormat_IMAGE',
    Audio = 'EnumMsgFormat_AUDIO',
    File = 'EnumMsgFormat_FILE',
    Comment = 'EnumMsgFormat_COMMENT'
}

export function EnumeratumConstantMsgFormatFromJSON(json: any): EnumeratumConstantMsgFormat {
    return EnumeratumConstantMsgFormatFromJSONTyped(json, false);
}

export function EnumeratumConstantMsgFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumConstantMsgFormat {
    return json as EnumeratumConstantMsgFormat;
}

export function EnumeratumConstantMsgFormatToJSON(value?: EnumeratumConstantMsgFormat | null): any {
    return value as any;
}

