/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumeratumCupSize {
    Tall = 'TALL',
    Grandi = 'GRANDI'
}

export function EnumeratumCupSizeFromJSON(json: any): EnumeratumCupSize {
    return EnumeratumCupSizeFromJSONTyped(json, false);
}

export function EnumeratumCupSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumCupSize {
    return json as EnumeratumCupSize;
}

export function EnumeratumCupSizeToJSON(value?: EnumeratumCupSize | null): any {
    return value as any;
}

