/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumeratumStarbuckOrderPaidStatus {
    Created = 'CREATED',
    Start = 'START',
    Finished = 'FINISHED'
}

export function EnumeratumStarbuckOrderPaidStatusFromJSON(json: any): EnumeratumStarbuckOrderPaidStatus {
    return EnumeratumStarbuckOrderPaidStatusFromJSONTyped(json, false);
}

export function EnumeratumStarbuckOrderPaidStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumStarbuckOrderPaidStatus {
    return json as EnumeratumStarbuckOrderPaidStatus;
}

export function EnumeratumStarbuckOrderPaidStatusToJSON(value?: EnumeratumStarbuckOrderPaidStatus | null): any {
    return value as any;
}

