/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumeratumShandianOrderAllStatus {
    Temp = 'TEMP',
    Created = 'CREATED',
    LocationFinish = 'LOCATION_FINISH',
    PaymentFinish = 'PAYMENT_FINISH',
    Canceled = 'CANCELED',
    SellFinished = 'SELL_FINISHED',
    StartWithdraw = 'START_WITHDRAW'
}

export function EnumeratumShandianOrderAllStatusFromJSON(json: any): EnumeratumShandianOrderAllStatus {
    return EnumeratumShandianOrderAllStatusFromJSONTyped(json, false);
}

export function EnumeratumShandianOrderAllStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumShandianOrderAllStatus {
    return json as EnumeratumShandianOrderAllStatus;
}

export function EnumeratumShandianOrderAllStatusToJSON(value?: EnumeratumShandianOrderAllStatus | null): any {
    return value as any;
}

