/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumTemperature {
    Hot = 'HOT',
    Cold = 'COLD'
}

export function EnumTemperatureFromJSON(json: any): EnumTemperature {
    return EnumTemperatureFromJSONTyped(json, false);
}

export function EnumTemperatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumTemperature {
    return json as EnumTemperature;
}

export function EnumTemperatureToJSON(value?: EnumTemperature | null): any {
    return value as any;
}

