/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumeratumTradeWay {
    Dxd = 'DXD',
    Qrcode = 'QRCODE'
}

export function EnumeratumTradeWayFromJSON(json: any): EnumeratumTradeWay {
    return EnumeratumTradeWayFromJSONTyped(json, false);
}

export function EnumeratumTradeWayFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumTradeWay {
    return json as EnumeratumTradeWay;
}

export function EnumeratumTradeWayToJSON(value?: EnumeratumTradeWay | null): any {
    return value as any;
}

