/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashLong
 */
export interface HashLong {
    /**
     * 
     * @type {number}
     * @memberof HashLong
     */
    id: number;
}

export function HashLongFromJSON(json: any): HashLong {
    return HashLongFromJSONTyped(json, false);
}

export function HashLongFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashLong {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function HashLongToJSON(value?: HashLong | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

