/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantChargeType,
    ConstantChargeTypeFromJSON,
    ConstantChargeTypeFromJSONTyped,
    ConstantChargeTypeToJSON,
} from './ConstantChargeType';
import {
    ConstantSeriesType,
    ConstantSeriesTypeFromJSON,
    ConstantSeriesTypeFromJSONTyped,
    ConstantSeriesTypeToJSON,
} from './ConstantSeriesType';
import {
    HashLong,
    HashLongFromJSON,
    HashLongFromJSONTyped,
    HashLongToJSON,
} from './HashLong';

/**
 * 
 * @export
 * @interface HorseSeriesReturn
 */
export interface HorseSeriesReturn {
    /**
     * 
     * @type {HashLong}
     * @memberof HorseSeriesReturn
     */
    id: HashLong;
    /**
     * 
     * @type {string}
     * @memberof HorseSeriesReturn
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof HorseSeriesReturn
     */
    authorId: string;
    /**
     * 
     * @type {ConstantSeriesType}
     * @memberof HorseSeriesReturn
     */
    seriesType: ConstantSeriesType;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    latestVersion: number;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    releaseVersion: number;
    /**
     * 
     * @type {string}
     * @memberof HorseSeriesReturn
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    learnPerDay?: number;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    categoryId?: number;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    subCategoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof HorseSeriesReturn
     */
    coverImageName?: string;
    /**
     * 
     * @type {ConstantChargeType}
     * @memberof HorseSeriesReturn
     */
    chargeType: ConstantChargeType;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    releaseCreateAt?: number;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    createAt: number;
    /**
     * 
     * @type {string}
     * @memberof HorseSeriesReturn
     */
    categoryName?: string;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    cardCount: number;
    /**
     * 
     * @type {number}
     * @memberof HorseSeriesReturn
     */
    subscriptionCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof HorseSeriesReturn
     */
    isDelete: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HorseSeriesReturn
     */
    visible: boolean;
    /**
     * 
     * @type {string}
     * @memberof HorseSeriesReturn
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof HorseSeriesReturn
     */
    releaseUpdate?: string;
    /**
     * 
     * @type {string}
     * @memberof HorseSeriesReturn
     */
    link: string;
}

export function HorseSeriesReturnFromJSON(json: any): HorseSeriesReturn {
    return HorseSeriesReturnFromJSONTyped(json, false);
}

export function HorseSeriesReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): HorseSeriesReturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': HashLongFromJSON(json['id']),
        'title': json['title'],
        'authorId': json['authorId'],
        'seriesType': ConstantSeriesTypeFromJSON(json['seriesType']),
        'latestVersion': json['latestVersion'],
        'releaseVersion': json['releaseVersion'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'learnPerDay': !exists(json, 'learnPerDay') ? undefined : json['learnPerDay'],
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'subCategoryId': !exists(json, 'subCategoryId') ? undefined : json['subCategoryId'],
        'coverImageName': !exists(json, 'coverImageName') ? undefined : json['coverImageName'],
        'chargeType': ConstantChargeTypeFromJSON(json['chargeType']),
        'releaseCreateAt': !exists(json, 'releaseCreateAt') ? undefined : json['releaseCreateAt'],
        'createAt': json['createAt'],
        'categoryName': !exists(json, 'categoryName') ? undefined : json['categoryName'],
        'cardCount': json['cardCount'],
        'subscriptionCount': json['subscriptionCount'],
        'isDelete': json['isDelete'],
        'visible': json['visible'],
        'groupId': json['groupId'],
        'releaseUpdate': !exists(json, 'releaseUpdate') ? undefined : json['releaseUpdate'],
        'link': json['link'],
    };
}

export function HorseSeriesReturnToJSON(value?: HorseSeriesReturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': HashLongToJSON(value.id),
        'title': value.title,
        'authorId': value.authorId,
        'seriesType': ConstantSeriesTypeToJSON(value.seriesType),
        'latestVersion': value.latestVersion,
        'releaseVersion': value.releaseVersion,
        'description': value.description,
        'learnPerDay': value.learnPerDay,
        'categoryId': value.categoryId,
        'subCategoryId': value.subCategoryId,
        'coverImageName': value.coverImageName,
        'chargeType': ConstantChargeTypeToJSON(value.chargeType),
        'releaseCreateAt': value.releaseCreateAt,
        'createAt': value.createAt,
        'categoryName': value.categoryName,
        'cardCount': value.cardCount,
        'subscriptionCount': value.subscriptionCount,
        'isDelete': value.isDelete,
        'visible': value.visible,
        'groupId': value.groupId,
        'releaseUpdate': value.releaseUpdate,
        'link': value.link,
    };
}

