/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    KunExercise,
    KunExerciseFromJSON,
    KunExerciseFromJSONTyped,
    KunExerciseToJSON,
} from './KunExercise';

/**
 * 
 * @export
 * @interface KunExerciseList
 */
export interface KunExerciseList {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof KunExerciseList
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof KunExerciseList
     */
    msg: string;
    /**
     * 
     * @type {Array<KunExercise>}
     * @memberof KunExerciseList
     */
    records?: Array<KunExercise>;
    /**
     * 
     * @type {number}
     * @memberof KunExerciseList
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof KunExerciseList
     */
    pageState?: string;
}

export function KunExerciseListFromJSON(json: any): KunExerciseList {
    return KunExerciseListFromJSONTyped(json, false);
}

export function KunExerciseListFromJSONTyped(json: any, ignoreDiscriminator: boolean): KunExerciseList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(KunExerciseFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function KunExerciseListToJSON(value?: KunExerciseList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(KunExerciseToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

