/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    PaymentHistory,
    PaymentHistoryFromJSON,
    PaymentHistoryFromJSONTyped,
    PaymentHistoryToJSON,
} from './PaymentHistory';

/**
 * 
 * @export
 * @interface ListPaymentHistory
 */
export interface ListPaymentHistory {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof ListPaymentHistory
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof ListPaymentHistory
     */
    msg: string;
    /**
     * 
     * @type {Array<PaymentHistory>}
     * @memberof ListPaymentHistory
     */
    records?: Array<PaymentHistory>;
    /**
     * 
     * @type {number}
     * @memberof ListPaymentHistory
     */
    pageState?: number;
    /**
     * 
     * @type {number}
     * @memberof ListPaymentHistory
     */
    prevPageMark?: number;
}

export function ListPaymentHistoryFromJSON(json: any): ListPaymentHistory {
    return ListPaymentHistoryFromJSONTyped(json, false);
}

export function ListPaymentHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPaymentHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(PaymentHistoryFromJSON)),
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
        'prevPageMark': !exists(json, 'prevPageMark') ? undefined : json['prevPageMark'],
    };
}

export function ListPaymentHistoryToJSON(value?: ListPaymentHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(PaymentHistoryToJSON)),
        'pageState': value.pageState,
        'prevPageMark': value.prevPageMark,
    };
}

