/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    HorseSeriesReturn,
    HorseSeriesReturnFromJSON,
    HorseSeriesReturnFromJSONTyped,
    HorseSeriesReturnToJSON,
} from './HorseSeriesReturn';

/**
 * 
 * @export
 * @interface NoSqlPagingListHorseSeriesReturn
 */
export interface NoSqlPagingListHorseSeriesReturn {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListHorseSeriesReturn
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListHorseSeriesReturn
     */
    msg: string;
    /**
     * 
     * @type {Array<HorseSeriesReturn>}
     * @memberof NoSqlPagingListHorseSeriesReturn
     */
    records?: Array<HorseSeriesReturn>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListHorseSeriesReturn
     */
    pageState?: number;
}

export function NoSqlPagingListHorseSeriesReturnFromJSON(json: any): NoSqlPagingListHorseSeriesReturn {
    return NoSqlPagingListHorseSeriesReturnFromJSONTyped(json, false);
}

export function NoSqlPagingListHorseSeriesReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListHorseSeriesReturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(HorseSeriesReturnFromJSON)),
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListHorseSeriesReturnToJSON(value?: NoSqlPagingListHorseSeriesReturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(HorseSeriesReturnToJSON)),
        'pageState': value.pageState,
    };
}

