/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    KunMessageReturn,
    KunMessageReturnFromJSON,
    KunMessageReturnFromJSONTyped,
    KunMessageReturnToJSON,
} from './KunMessageReturn';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataKunMessageReturn
 */
export interface NoSqlPagingListDataKunMessageReturn {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataKunMessageReturn
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataKunMessageReturn
     */
    msg: string;
    /**
     * 
     * @type {Array<KunMessageReturn>}
     * @memberof NoSqlPagingListDataKunMessageReturn
     */
    records?: Array<KunMessageReturn>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataKunMessageReturn
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataKunMessageReturn
     */
    pageState?: string;
}

export function NoSqlPagingListDataKunMessageReturnFromJSON(json: any): NoSqlPagingListDataKunMessageReturn {
    return NoSqlPagingListDataKunMessageReturnFromJSONTyped(json, false);
}

export function NoSqlPagingListDataKunMessageReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataKunMessageReturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(KunMessageReturnFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataKunMessageReturnToJSON(value?: NoSqlPagingListDataKunMessageReturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(KunMessageReturnToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

