/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    ShandianItem,
    ShandianItemFromJSON,
    ShandianItemFromJSONTyped,
    ShandianItemToJSON,
} from './ShandianItem';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataShandianItem
 */
export interface NoSqlPagingListDataShandianItem {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataShandianItem
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataShandianItem
     */
    msg: string;
    /**
     * 
     * @type {Array<ShandianItem>}
     * @memberof NoSqlPagingListDataShandianItem
     */
    records?: Array<ShandianItem>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataShandianItem
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataShandianItem
     */
    pageState?: string;
}

export function NoSqlPagingListDataShandianItemFromJSON(json: any): NoSqlPagingListDataShandianItem {
    return NoSqlPagingListDataShandianItemFromJSONTyped(json, false);
}

export function NoSqlPagingListDataShandianItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataShandianItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(ShandianItemFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataShandianItemToJSON(value?: NoSqlPagingListDataShandianItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(ShandianItemToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

