/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    ReqCreateShandianOrder,
    ReqCreateShandianOrderFromJSON,
    ReqCreateShandianOrderFromJSONTyped,
    ReqCreateShandianOrderToJSON,
} from './ReqCreateShandianOrder';

/**
 * 
 * @export
 * @interface OptionDataReqCreateShandianOrder
 */
export interface OptionDataReqCreateShandianOrder {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof OptionDataReqCreateShandianOrder
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof OptionDataReqCreateShandianOrder
     */
    msg: string;
    /**
     * 
     * @type {ReqCreateShandianOrder}
     * @memberof OptionDataReqCreateShandianOrder
     */
    record?: ReqCreateShandianOrder;
}

export function OptionDataReqCreateShandianOrderFromJSON(json: any): OptionDataReqCreateShandianOrder {
    return OptionDataReqCreateShandianOrderFromJSONTyped(json, false);
}

export function OptionDataReqCreateShandianOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionDataReqCreateShandianOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'record': !exists(json, 'record') ? undefined : ReqCreateShandianOrderFromJSON(json['record']),
    };
}

export function OptionDataReqCreateShandianOrderToJSON(value?: OptionDataReqCreateShandianOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'record': ReqCreateShandianOrderToJSON(value.record),
    };
}

