/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    KunExercise,
    KunExerciseFromJSON,
    KunExerciseFromJSONTyped,
    KunExerciseToJSON,
} from './KunExercise';

/**
 * 
 * @export
 * @interface OptionDataKunExercise
 */
export interface OptionDataKunExercise {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof OptionDataKunExercise
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof OptionDataKunExercise
     */
    msg: string;
    /**
     * 
     * @type {KunExercise}
     * @memberof OptionDataKunExercise
     */
    record?: KunExercise;
}

export function OptionDataKunExerciseFromJSON(json: any): OptionDataKunExercise {
    return OptionDataKunExerciseFromJSONTyped(json, false);
}

export function OptionDataKunExerciseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionDataKunExercise {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'record': !exists(json, 'record') ? undefined : KunExerciseFromJSON(json['record']),
    };
}

export function OptionDataKunExerciseToJSON(value?: OptionDataKunExercise | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'record': KunExerciseToJSON(value.record),
    };
}

