/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    KunAudioReadLog,
    KunAudioReadLogFromJSON,
    KunAudioReadLogFromJSONTyped,
    KunAudioReadLogToJSON,
} from './KunAudioReadLog';

/**
 * 
 * @export
 * @interface OptionDataKunAudioReadLog
 */
export interface OptionDataKunAudioReadLog {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof OptionDataKunAudioReadLog
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof OptionDataKunAudioReadLog
     */
    msg: string;
    /**
     * 
     * @type {KunAudioReadLog}
     * @memberof OptionDataKunAudioReadLog
     */
    record?: KunAudioReadLog;
}

export function OptionDataKunAudioReadLogFromJSON(json: any): OptionDataKunAudioReadLog {
    return OptionDataKunAudioReadLogFromJSONTyped(json, false);
}

export function OptionDataKunAudioReadLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionDataKunAudioReadLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'record': !exists(json, 'record') ? undefined : KunAudioReadLogFromJSON(json['record']),
    };
}

export function OptionDataKunAudioReadLogToJSON(value?: OptionDataKunAudioReadLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'record': KunAudioReadLogToJSON(value.record),
    };
}

