/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    ShandianOrder,
    ShandianOrderFromJSON,
    ShandianOrderFromJSONTyped,
    ShandianOrderToJSON,
} from './ShandianOrder';

/**
 * 
 * @export
 * @interface OptionDataShandianOrder
 */
export interface OptionDataShandianOrder {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof OptionDataShandianOrder
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof OptionDataShandianOrder
     */
    msg: string;
    /**
     * 
     * @type {ShandianOrder}
     * @memberof OptionDataShandianOrder
     */
    record?: ShandianOrder;
}

export function OptionDataShandianOrderFromJSON(json: any): OptionDataShandianOrder {
    return OptionDataShandianOrderFromJSONTyped(json, false);
}

export function OptionDataShandianOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionDataShandianOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'record': !exists(json, 'record') ? undefined : ShandianOrderFromJSON(json['record']),
    };
}

export function OptionDataShandianOrderToJSON(value?: OptionDataShandianOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'record': ShandianOrderToJSON(value.record),
    };
}

