/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantPaymentStatus,
    ConstantPaymentStatusFromJSON,
    ConstantPaymentStatusFromJSONTyped,
    ConstantPaymentStatusToJSON,
} from './ConstantPaymentStatus';

/**
 * 
 * @export
 * @interface PaymentHistory
 */
export interface PaymentHistory {
    /**
     * 
     * @type {number}
     * @memberof PaymentHistory
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentHistory
     */
    channelId: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentHistory
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentHistory
     */
    seriesId: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentHistory
     */
    createAt: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentHistory
     */
    title: string;
    /**
     * 
     * @type {ConstantPaymentStatus}
     * @memberof PaymentHistory
     */
    status: ConstantPaymentStatus;
    /**
     * 
     * @type {number}
     * @memberof PaymentHistory
     */
    payAmount: number;
}

export function PaymentHistoryFromJSON(json: any): PaymentHistory {
    return PaymentHistoryFromJSONTyped(json, false);
}

export function PaymentHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'channelId': json['channelId'],
        'userId': json['userId'],
        'seriesId': json['seriesId'],
        'createAt': json['createAt'],
        'title': json['title'],
        'status': ConstantPaymentStatusFromJSON(json['status']),
        'payAmount': json['payAmount'],
    };
}

export function PaymentHistoryToJSON(value?: PaymentHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'channelId': value.channelId,
        'userId': value.userId,
        'seriesId': value.seriesId,
        'createAt': value.createAt,
        'title': value.title,
        'status': ConstantPaymentStatusToJSON(value.status),
        'payAmount': value.payAmount,
    };
}

