/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';

/**
 * 
 * @export
 * @interface RetMsg
 */
export interface RetMsg {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof RetMsg
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof RetMsg
     */
    msg: string;
}

export function RetMsgFromJSON(json: any): RetMsg {
    return RetMsgFromJSONTyped(json, false);
}

export function RetMsgFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetMsg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
    };
}

export function RetMsgToJSON(value?: RetMsg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
    };
}

