/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnumeratumBrand,
    EnumeratumBrandFromJSON,
    EnumeratumBrandFromJSONTyped,
    EnumeratumBrandToJSON,
} from './EnumeratumBrand';

/**
 * 
 * @export
 * @interface ShandianBrandItem
 */
export interface ShandianBrandItem {
    /**
     * 
     * @type {EnumeratumBrand}
     * @memberof ShandianBrandItem
     */
    id: EnumeratumBrand;
    /**
     * 
     * @type {string}
     * @memberof ShandianBrandItem
     */
    name: string;
}

export function ShandianBrandItemFromJSON(json: any): ShandianBrandItem {
    return ShandianBrandItemFromJSONTyped(json, false);
}

export function ShandianBrandItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShandianBrandItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': EnumeratumBrandFromJSON(json['id']),
        'name': json['name'],
    };
}

export function ShandianBrandItemToJSON(value?: ShandianBrandItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': EnumeratumBrandToJSON(value.id),
        'name': value.name,
    };
}

