/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnumeratumStarbuckOrderPaidStatus,
    EnumeratumStarbuckOrderPaidStatusFromJSON,
    EnumeratumStarbuckOrderPaidStatusFromJSONTyped,
    EnumeratumStarbuckOrderPaidStatusToJSON,
} from './EnumeratumStarbuckOrderPaidStatus';

/**
 * 
 * @export
 * @interface StarbuckPaidOrder
 */
export interface StarbuckPaidOrder {
    /**
     * 
     * @type {number}
     * @memberof StarbuckPaidOrder
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof StarbuckPaidOrder
     */
    orderId: string;
    /**
     * 
     * @type {number}
     * @memberof StarbuckPaidOrder
     */
    createAt: number;
    /**
     * 
     * @type {string}
     * @memberof StarbuckPaidOrder
     */
    taobaoId: string;
    /**
     * 
     * @type {number}
     * @memberof StarbuckPaidOrder
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof StarbuckPaidOrder
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof StarbuckPaidOrder
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof StarbuckPaidOrder
     */
    phone: string;
    /**
     * 
     * @type {number}
     * @memberof StarbuckPaidOrder
     */
    kunOrderId?: number;
    /**
     * 
     * @type {EnumeratumStarbuckOrderPaidStatus}
     * @memberof StarbuckPaidOrder
     */
    status: EnumeratumStarbuckOrderPaidStatus;
    /**
     * 
     * @type {string}
     * @memberof StarbuckPaidOrder
     */
    title?: string;
}

export function StarbuckPaidOrderFromJSON(json: any): StarbuckPaidOrder {
    return StarbuckPaidOrderFromJSONTyped(json, false);
}

export function StarbuckPaidOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarbuckPaidOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orderId': json['orderId'],
        'createAt': json['createAt'],
        'taobaoId': json['taobaoId'],
        'price': json['price'],
        'userId': json['userId'],
        'userName': json['userName'],
        'phone': json['phone'],
        'kunOrderId': !exists(json, 'kunOrderId') ? undefined : json['kunOrderId'],
        'status': EnumeratumStarbuckOrderPaidStatusFromJSON(json['status']),
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function StarbuckPaidOrderToJSON(value?: StarbuckPaidOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'orderId': value.orderId,
        'createAt': value.createAt,
        'taobaoId': value.taobaoId,
        'price': value.price,
        'userId': value.userId,
        'userName': value.userName,
        'phone': value.phone,
        'kunOrderId': value.kunOrderId,
        'status': EnumeratumStarbuckOrderPaidStatusToJSON(value.status),
        'title': value.title,
    };
}

