/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StarbuckAddress,
    StarbuckAddressFromJSON,
    StarbuckAddressFromJSONTyped,
    StarbuckAddressToJSON,
} from './StarbuckAddress';
import {
    StarbuckLocation,
    StarbuckLocationFromJSON,
    StarbuckLocationFromJSONTyped,
    StarbuckLocationToJSON,
} from './StarbuckLocation';
import {
    StarbuckOpenClose,
    StarbuckOpenCloseFromJSON,
    StarbuckOpenCloseFromJSONTyped,
    StarbuckOpenCloseToJSON,
} from './StarbuckOpenClose';

/**
 * 
 * @export
 * @interface StarbuckStore
 */
export interface StarbuckStore {
    /**
     * 
     * @type {string}
     * @memberof StarbuckStore
     */
    name: string;
    /**
     * 
     * @type {StarbuckAddress}
     * @memberof StarbuckStore
     */
    address: StarbuckAddress;
    /**
     * 
     * @type {StarbuckOpenClose}
     * @memberof StarbuckStore
     */
    today: StarbuckOpenClose;
    /**
     * 
     * @type {StarbuckLocation}
     * @memberof StarbuckStore
     */
    coordinates: StarbuckLocation;
    /**
     * 
     * @type {string}
     * @memberof StarbuckStore
     */
    storeNumber: string;
}

export function StarbuckStoreFromJSON(json: any): StarbuckStore {
    return StarbuckStoreFromJSONTyped(json, false);
}

export function StarbuckStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarbuckStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': StarbuckAddressFromJSON(json['address']),
        'today': StarbuckOpenCloseFromJSON(json['today']),
        'coordinates': StarbuckLocationFromJSON(json['coordinates']),
        'storeNumber': json['storeNumber'],
    };
}

export function StarbuckStoreToJSON(value?: StarbuckStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'address': StarbuckAddressToJSON(value.address),
        'today': StarbuckOpenCloseToJSON(value.today),
        'coordinates': StarbuckLocationToJSON(value.coordinates),
        'storeNumber': value.storeNumber,
    };
}

