/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AglosticCaigouItem
 */
export interface AglosticCaigouItem {
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    orderId: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    skuName: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    skuCode: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    skuId?: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    productName: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    buyerId: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    cost: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItem
     */
    creatAt: string;
}

export function AglosticCaigouItemFromJSON(json: any): AglosticCaigouItem {
    return AglosticCaigouItemFromJSONTyped(json, false);
}

export function AglosticCaigouItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AglosticCaigouItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'id': json['id'],
        'phone': json['phone'],
        'skuName': json['skuName'],
        'skuCode': json['skuCode'],
        'skuId': !exists(json, 'skuId') ? undefined : json['skuId'],
        'productName': json['productName'],
        'productId': json['productId'],
        'buyerId': json['buyerId'],
        'cost': json['cost'],
        'creatAt': json['creatAt'],
    };
}

export function AglosticCaigouItemToJSON(value?: AglosticCaigouItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderId': value.orderId,
        'id': value.id,
        'phone': value.phone,
        'skuName': value.skuName,
        'skuCode': value.skuCode,
        'skuId': value.skuId,
        'productName': value.productName,
        'productId': value.productId,
        'buyerId': value.buyerId,
        'cost': value.cost,
        'creatAt': value.creatAt,
    };
}

