/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnumeratumStarbuckItem,
    EnumeratumStarbuckItemFromJSON,
    EnumeratumStarbuckItemFromJSONTyped,
    EnumeratumStarbuckItemToJSON,
} from './EnumeratumStarbuckItem';

/**
 * 
 * @export
 * @interface AglosticCaigouItemSignedAndStarkbuckItem
 */
export interface AglosticCaigouItemSignedAndStarkbuckItem {
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    orderId: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    skuName: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    skuCode: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    skuId?: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    productName: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    buyerId: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    cost: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    creatAt: string;
    /**
     * 
     * @type {string}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    sign: string;
    /**
     * 
     * @type {EnumeratumStarbuckItem}
     * @memberof AglosticCaigouItemSignedAndStarkbuckItem
     */
    item: EnumeratumStarbuckItem;
}

export function AglosticCaigouItemSignedAndStarkbuckItemFromJSON(json: any): AglosticCaigouItemSignedAndStarkbuckItem {
    return AglosticCaigouItemSignedAndStarkbuckItemFromJSONTyped(json, false);
}

export function AglosticCaigouItemSignedAndStarkbuckItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AglosticCaigouItemSignedAndStarkbuckItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'id': json['id'],
        'phone': json['phone'],
        'skuName': json['skuName'],
        'skuCode': json['skuCode'],
        'skuId': !exists(json, 'skuId') ? undefined : json['skuId'],
        'productName': json['productName'],
        'productId': json['productId'],
        'buyerId': json['buyerId'],
        'cost': json['cost'],
        'creatAt': json['creatAt'],
        'sign': json['sign'],
        'item': EnumeratumStarbuckItemFromJSON(json['item']),
    };
}

export function AglosticCaigouItemSignedAndStarkbuckItemToJSON(value?: AglosticCaigouItemSignedAndStarkbuckItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderId': value.orderId,
        'id': value.id,
        'phone': value.phone,
        'skuName': value.skuName,
        'skuCode': value.skuCode,
        'skuId': value.skuId,
        'productName': value.productName,
        'productId': value.productId,
        'buyerId': value.buyerId,
        'cost': value.cost,
        'creatAt': value.creatAt,
        'sign': value.sign,
        'item': EnumeratumStarbuckItemToJSON(value.item),
    };
}

