/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ASearchStore
 */
export interface ASearchStore {
    /**
     * 
     * @type {string}
     * @memberof ASearchStore
     */
    storecode: string;
    /**
     * 
     * @type {string}
     * @memberof ASearchStore
     */
    storename: string;
    /**
     * 
     * @type {number}
     * @memberof ASearchStore
     */
    distance: number;
    /**
     * 
     * @type {string}
     * @memberof ASearchStore
     */
    cityName: string;
    /**
     * 
     * @type {string}
     * @memberof ASearchStore
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof ASearchStore
     */
    lat: string;
    /**
     * 
     * @type {string}
     * @memberof ASearchStore
     */
    lng: string;
}

export function ASearchStoreFromJSON(json: any): ASearchStore {
    return ASearchStoreFromJSONTyped(json, false);
}

export function ASearchStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): ASearchStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'storecode': json['storecode'],
        'storename': json['storename'],
        'distance': json['distance'],
        'cityName': json['cityName'],
        'address': json['address'],
        'lat': json['lat'],
        'lng': json['lng'],
    };
}

export function ASearchStoreToJSON(value?: ASearchStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'storecode': value.storecode,
        'storename': value.storename,
        'distance': value.distance,
        'cityName': value.cityName,
        'address': value.address,
        'lat': value.lat,
        'lng': value.lng,
    };
}

