/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ConstantSeriesType = {
    Memory: 'memory',
    Read: 'read',
    Practise: 'practise'
} as const;
export type ConstantSeriesType = typeof ConstantSeriesType[keyof typeof ConstantSeriesType];


export function ConstantSeriesTypeFromJSON(json: any): ConstantSeriesType {
    return ConstantSeriesTypeFromJSONTyped(json, false);
}

export function ConstantSeriesTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstantSeriesType {
    return json as ConstantSeriesType;
}

export function ConstantSeriesTypeToJSON(value?: ConstantSeriesType | null): any {
    return value as any;
}

