/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentHistory
 */
export interface CreatePaymentHistory {
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentHistory
     */
    money: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentHistory
     */
    channelId: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentHistory
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentHistory
     */
    seriesId: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentHistory
     */
    createAt: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentHistory
     */
    title: string;
}

export function CreatePaymentHistoryFromJSON(json: any): CreatePaymentHistory {
    return CreatePaymentHistoryFromJSONTyped(json, false);
}

export function CreatePaymentHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'money': json['money'],
        'channelId': json['channelId'],
        'userId': json['userId'],
        'seriesId': json['seriesId'],
        'createAt': json['createAt'],
        'title': json['title'],
    };
}

export function CreatePaymentHistoryToJSON(value?: CreatePaymentHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'money': value.money,
        'channelId': value.channelId,
        'userId': value.userId,
        'seriesId': value.seriesId,
        'createAt': value.createAt,
        'title': value.title,
    };
}

