/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumeratumCat {
    Drink = 'DRINK',
    Rice = 'RICE',
    Xiaochi = 'XIAOCHI'
}

export function EnumeratumCatFromJSON(json: any): EnumeratumCat {
    return EnumeratumCatFromJSONTyped(json, false);
}

export function EnumeratumCatFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumCat {
    return json as EnumeratumCat;
}

export function EnumeratumCatToJSON(value?: EnumeratumCat | null): any {
    return value as any;
}

