/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EnumeratumStarItem {
    HongchaLatte = 'HONGCHA_Latte',
    MochaLatte = 'MOCHA_Latte',
    Latte = 'Latte',
    Moca = 'MOCA',
    Americano = 'Americano',
    FlatWhite = 'FlatWhite'
}

export function EnumeratumStarItemFromJSON(json: any): EnumeratumStarItem {
    return EnumeratumStarItemFromJSONTyped(json, false);
}

export function EnumeratumStarItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumStarItem {
    return json as EnumeratumStarItem;
}

export function EnumeratumStarItemToJSON(value?: EnumeratumStarItem | null): any {
    return value as any;
}

