/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EnumeratumStarbuckOrderPaidStatus = {
    Created: 'CREATED',
    Start: 'START',
    Finished: 'FINISHED'
} as const;
export type EnumeratumStarbuckOrderPaidStatus = typeof EnumeratumStarbuckOrderPaidStatus[keyof typeof EnumeratumStarbuckOrderPaidStatus];


export function EnumeratumStarbuckOrderPaidStatusFromJSON(json: any): EnumeratumStarbuckOrderPaidStatus {
    return EnumeratumStarbuckOrderPaidStatusFromJSONTyped(json, false);
}

export function EnumeratumStarbuckOrderPaidStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumStarbuckOrderPaidStatus {
    return json as EnumeratumStarbuckOrderPaidStatus;
}

export function EnumeratumStarbuckOrderPaidStatusToJSON(value?: EnumeratumStarbuckOrderPaidStatus | null): any {
    return value as any;
}

