/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EnumeratumChatRole = {
    Publisher: 'Role_Publisher',
    Subscriber: 'Role_Subscriber',
    Admin: 'Role_Admin'
} as const;
export type EnumeratumChatRole = typeof EnumeratumChatRole[keyof typeof EnumeratumChatRole];


export function EnumeratumChatRoleFromJSON(json: any): EnumeratumChatRole {
    return EnumeratumChatRoleFromJSONTyped(json, false);
}

export function EnumeratumChatRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumChatRole {
    return json as EnumeratumChatRole;
}

export function EnumeratumChatRoleToJSON(value?: EnumeratumChatRole | null): any {
    return value as any;
}

