/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EnumeratumStarbuckItem = {
    HongchaLatte: 'HONGCHA_Latte',
    MochaLatte: 'MOCHA_Latte',
    LatteCoffee: 'LatteCoffee',
    Moca: 'MOCA',
    Americano: 'Americano',
    FlatWhite: 'FlatWhite'
} as const;
export type EnumeratumStarbuckItem = typeof EnumeratumStarbuckItem[keyof typeof EnumeratumStarbuckItem];


export function EnumeratumStarbuckItemFromJSON(json: any): EnumeratumStarbuckItem {
    return EnumeratumStarbuckItemFromJSONTyped(json, false);
}

export function EnumeratumStarbuckItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumStarbuckItem {
    return json as EnumeratumStarbuckItem;
}

export function EnumeratumStarbuckItemToJSON(value?: EnumeratumStarbuckItem | null): any {
    return value as any;
}

