/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EnumeratumStarbuckCat = {
    Xingbingle: 'XINGBINGLE',
    Latte: 'LATTE'
} as const;
export type EnumeratumStarbuckCat = typeof EnumeratumStarbuckCat[keyof typeof EnumeratumStarbuckCat];


export function EnumeratumStarbuckCatFromJSON(json: any): EnumeratumStarbuckCat {
    return EnumeratumStarbuckCatFromJSONTyped(json, false);
}

export function EnumeratumStarbuckCatFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumeratumStarbuckCat {
    return json as EnumeratumStarbuckCat;
}

export function EnumeratumStarbuckCatToJSON(value?: EnumeratumStarbuckCat | null): any {
    return value as any;
}

