/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserInfo
 */
export interface GetUserInfo {
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo
     */
    appid: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo
     */
    sessionKey: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo
     */
    signature: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo
     */
    rowData: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo
     */
    encryptedData: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo
     */
    iv: string;
}

export function GetUserInfoFromJSON(json: any): GetUserInfo {
    return GetUserInfoFromJSONTyped(json, false);
}

export function GetUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appid': json['appid'],
        'sessionKey': json['session_key'],
        'signature': json['signature'],
        'rowData': json['rowData'],
        'encryptedData': json['encryptedData'],
        'iv': json['iv'],
    };
}

export function GetUserInfoToJSON(value?: GetUserInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appid': value.appid,
        'session_key': value.sessionKey,
        'signature': value.signature,
        'rowData': value.rowData,
        'encryptedData': value.encryptedData,
        'iv': value.iv,
    };
}

