/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HorseSeriesSortType = {
    DefaultSort: 'defaultSort',
    DateAsc: 'dateAsc',
    DateDesc: 'dateDesc',
    PriceDesc: 'priceDesc',
    PriceAsc: 'priceAsc',
    ConcernCountDesc: 'concernCountDesc'
} as const;
export type HorseSeriesSortType = typeof HorseSeriesSortType[keyof typeof HorseSeriesSortType];


export function HorseSeriesSortTypeFromJSON(json: any): HorseSeriesSortType {
    return HorseSeriesSortTypeFromJSONTyped(json, false);
}

export function HorseSeriesSortTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HorseSeriesSortType {
    return json as HorseSeriesSortType;
}

export function HorseSeriesSortTypeToJSON(value?: HorseSeriesSortType | null): any {
    return value as any;
}

