/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KunAudioReadLog
 */
export interface KunAudioReadLog {
    /**
     * 
     * @type {number}
     * @memberof KunAudioReadLog
     */
    channelId: number;
    /**
     * 
     * @type {string}
     * @memberof KunAudioReadLog
     */
    feedId: string;
    /**
     * 
     * @type {string}
     * @memberof KunAudioReadLog
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof KunAudioReadLog
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof KunAudioReadLog
     */
    updateAt: number;
}

export function KunAudioReadLogFromJSON(json: any): KunAudioReadLog {
    return KunAudioReadLogFromJSONTyped(json, false);
}

export function KunAudioReadLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): KunAudioReadLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelId': json['channelId'],
        'feedId': json['feedId'],
        'userId': json['userId'],
        'offset': json['offset'],
        'updateAt': json['updateAt'],
    };
}

export function KunAudioReadLogToJSON(value?: KunAudioReadLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channelId': value.channelId,
        'feedId': value.feedId,
        'userId': value.userId,
        'offset': value.offset,
        'updateAt': value.updateAt,
    };
}

