/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnumeratumBenifitCardItem,
    EnumeratumBenifitCardItemFromJSON,
    EnumeratumBenifitCardItemFromJSONTyped,
    EnumeratumBenifitCardItemToJSON,
} from './EnumeratumBenifitCardItem';
import {
    EnumeratumValidStatus,
    EnumeratumValidStatusFromJSON,
    EnumeratumValidStatusFromJSONTyped,
    EnumeratumValidStatusToJSON,
} from './EnumeratumValidStatus';

/**
 * 
 * @export
 * @interface KunBenefitCard
 */
export interface KunBenefitCard {
    /**
     * 
     * @type {number}
     * @memberof KunBenefitCard
     */
    channelId: number;
    /**
     * 
     * @type {string}
     * @memberof KunBenefitCard
     */
    userId: string;
    /**
     * 
     * @type {EnumeratumBenifitCardItem}
     * @memberof KunBenefitCard
     */
    card: EnumeratumBenifitCardItem;
    /**
     * 
     * @type {EnumeratumValidStatus}
     * @memberof KunBenefitCard
     */
    status: EnumeratumValidStatus;
    /**
     * 
     * @type {number}
     * @memberof KunBenefitCard
     */
    createAt: number;
    /**
     * 
     * @type {number}
     * @memberof KunBenefitCard
     */
    updateAt: number;
    /**
     * 
     * @type {number}
     * @memberof KunBenefitCard
     */
    expiredAt: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof KunBenefitCard
     */
    paymentList?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof KunBenefitCard
     */
    savedMoney: number;
}

export function KunBenefitCardFromJSON(json: any): KunBenefitCard {
    return KunBenefitCardFromJSONTyped(json, false);
}

export function KunBenefitCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): KunBenefitCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelId': json['channelId'],
        'userId': json['userId'],
        'card': EnumeratumBenifitCardItemFromJSON(json['card']),
        'status': EnumeratumValidStatusFromJSON(json['status']),
        'createAt': json['createAt'],
        'updateAt': json['updateAt'],
        'expiredAt': json['expiredAt'],
        'paymentList': !exists(json, 'paymentList') ? undefined : json['paymentList'],
        'savedMoney': json['savedMoney'],
    };
}

export function KunBenefitCardToJSON(value?: KunBenefitCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channelId': value.channelId,
        'userId': value.userId,
        'card': EnumeratumBenifitCardItemToJSON(value.card),
        'status': EnumeratumValidStatusToJSON(value.status),
        'createAt': value.createAt,
        'updateAt': value.updateAt,
        'expiredAt': value.expiredAt,
        'paymentList': value.paymentList,
        'savedMoney': value.savedMoney,
    };
}

