/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KunPinCard
 */
export interface KunPinCard {
    /**
     * 
     * @type {number}
     * @memberof KunPinCard
     */
    channelId: number;
    /**
     * 
     * @type {string}
     * @memberof KunPinCard
     */
    seriesId: string;
    /**
     * 
     * @type {string}
     * @memberof KunPinCard
     */
    postId: string;
    /**
     * 
     * @type {number}
     * @memberof KunPinCard
     */
    cardOrder: number;
    /**
     * 
     * @type {string}
     * @memberof KunPinCard
     */
    title: string;
}

export function KunPinCardFromJSON(json: any): KunPinCard {
    return KunPinCardFromJSONTyped(json, false);
}

export function KunPinCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): KunPinCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelId': json['channelId'],
        'seriesId': json['seriesId'],
        'postId': json['postId'],
        'cardOrder': json['cardOrder'],
        'title': json['title'],
    };
}

export function KunPinCardToJSON(value?: KunPinCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channelId': value.channelId,
        'seriesId': value.seriesId,
        'postId': value.postId,
        'cardOrder': value.cardOrder,
        'title': value.title,
    };
}

