/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnumeratumShandianOrderAllStatus,
    EnumeratumShandianOrderAllStatusFromJSON,
    EnumeratumShandianOrderAllStatusFromJSONTyped,
    EnumeratumShandianOrderAllStatusToJSON,
} from './EnumeratumShandianOrderAllStatus';

/**
 * 
 * @export
 * @interface KunSimpleOrder
 */
export interface KunSimpleOrder {
    /**
     * 
     * @type {number}
     * @memberof KunSimpleOrder
     */
    channelId: number;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    orderId: string;
    /**
     * 
     * @type {number}
     * @memberof KunSimpleOrder
     */
    buyNum: number;
    /**
     * 
     * @type {number}
     * @memberof KunSimpleOrder
     */
    updateAt: number;
    /**
     * 
     * @type {number}
     * @memberof KunSimpleOrder
     */
    createAt: number;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    goodsid: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof KunSimpleOrder
     */
    paidMoney: number;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    outOrderId: string;
    /**
     * 
     * @type {EnumeratumShandianOrderAllStatus}
     * @memberof KunSimpleOrder
     */
    orderStatus: EnumeratumShandianOrderAllStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof KunSimpleOrder
     */
    attachments?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    receipt: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    refundstatus: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    refundreceipt?: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    statusDescription?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof KunSimpleOrder
     */
    cardlists?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    taobaoOrderId: string;
    /**
     * 
     * @type {string}
     * @memberof KunSimpleOrder
     */
    taobaoUserName: string;
}

export function KunSimpleOrderFromJSON(json: any): KunSimpleOrder {
    return KunSimpleOrderFromJSONTyped(json, false);
}

export function KunSimpleOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): KunSimpleOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelId': json['channelId'],
        'userId': json['userId'],
        'orderId': json['orderId'],
        'buyNum': json['buyNum'],
        'updateAt': json['updateAt'],
        'createAt': json['createAt'],
        'title': json['title'],
        'goodsid': json['goodsid'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'paidMoney': json['paidMoney'],
        'outOrderId': json['outOrderId'],
        'orderStatus': EnumeratumShandianOrderAllStatusFromJSON(json['orderStatus']),
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'receipt': json['receipt'],
        'refundstatus': json['refundstatus'],
        'refundreceipt': !exists(json, 'refundreceipt') ? undefined : json['refundreceipt'],
        'statusDescription': !exists(json, 'statusDescription') ? undefined : json['statusDescription'],
        'cardlists': !exists(json, 'cardlists') ? undefined : json['cardlists'],
        'taobaoOrderId': json['taobaoOrderId'],
        'taobaoUserName': json['taobaoUserName'],
    };
}

export function KunSimpleOrderToJSON(value?: KunSimpleOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channelId': value.channelId,
        'userId': value.userId,
        'orderId': value.orderId,
        'buyNum': value.buyNum,
        'updateAt': value.updateAt,
        'createAt': value.createAt,
        'title': value.title,
        'goodsid': value.goodsid,
        'description': value.description,
        'paidMoney': value.paidMoney,
        'outOrderId': value.outOrderId,
        'orderStatus': EnumeratumShandianOrderAllStatusToJSON(value.orderStatus),
        'attachments': value.attachments,
        'phone': value.phone,
        'address': value.address,
        'imageUrl': value.imageUrl,
        'receipt': value.receipt,
        'refundstatus': value.refundstatus,
        'refundreceipt': value.refundreceipt,
        'statusDescription': value.statusDescription,
        'cardlists': value.cardlists,
        'taobaoOrderId': value.taobaoOrderId,
        'taobaoUserName': value.taobaoUserName,
    };
}

