/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantGenderStatus,
    ConstantGenderStatusFromJSON,
    ConstantGenderStatusFromJSONTyped,
    ConstantGenderStatusToJSON,
} from './ConstantGenderStatus';

/**
 * 
 * @export
 * @interface KunUser
 */
export interface KunUser {
    /**
     * 
     * @type {number}
     * @memberof KunUser
     */
    channelId: number;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    userName?: string;
    /**
     * 
     * @type {ConstantGenderStatus}
     * @memberof KunUser
     */
    gender?: ConstantGenderStatus;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    nickName?: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    slogan?: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    thumbnail?: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    verifiedRole?: string;
    /**
     * 
     * @type {string}
     * @memberof KunUser
     */
    locationName?: string;
}

export function KunUserFromJSON(json: any): KunUser {
    return KunUserFromJSONTyped(json, false);
}

export function KunUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): KunUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelId': json['channelId'],
        'userId': json['userId'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'gender': !exists(json, 'gender') ? undefined : ConstantGenderStatusFromJSON(json['gender']),
        'password': !exists(json, 'password') ? undefined : json['password'],
        'nickName': !exists(json, 'nickName') ? undefined : json['nickName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'slogan': !exists(json, 'slogan') ? undefined : json['slogan'],
        'thumbnail': !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'verifiedRole': !exists(json, 'verifiedRole') ? undefined : json['verifiedRole'],
        'locationName': !exists(json, 'locationName') ? undefined : json['locationName'],
    };
}

export function KunUserToJSON(value?: KunUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channelId': value.channelId,
        'userId': value.userId,
        'userName': value.userName,
        'gender': ConstantGenderStatusToJSON(value.gender),
        'password': value.password,
        'nickName': value.nickName,
        'email': value.email,
        'phone': value.phone,
        'slogan': value.slogan,
        'thumbnail': value.thumbnail,
        'location': value.location,
        'verifiedRole': value.verifiedRole,
        'locationName': value.locationName,
    };
}

