/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    HorseSeriesReturn,
    HorseSeriesReturnFromJSON,
    HorseSeriesReturnFromJSONTyped,
    HorseSeriesReturnToJSON,
} from './HorseSeriesReturn';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn
 */
export interface NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn
     */
    msg: string;
    /**
     * 
     * @type {Array<HorseSeriesReturn>}
     * @memberof NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn
     */
    records?: Array<HorseSeriesReturn>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn
     */
    pageState?: number;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn
     */
    prevPageMark?: number;
}

export function NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturnFromJSON(json: any): NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn {
    return NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturnFromJSONTyped(json, false);
}

export function NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(HorseSeriesReturnFromJSON)),
        'total': !exists(json, 'total') ? undefined : json['total'],
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
        'prevPageMark': !exists(json, 'prevPageMark') ? undefined : json['prevPageMark'],
    };
}

export function NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturnToJSON(value?: NoSqlPagingListDataPageMarkDateTimeHorseSeriesReturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(HorseSeriesReturnToJSON)),
        'total': value.total,
        'pageSize': value.pageSize,
        'pageState': value.pageState,
        'prevPageMark': value.prevPageMark,
    };
}

