/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    ShopItemDescription,
    ShopItemDescriptionFromJSON,
    ShopItemDescriptionFromJSONTyped,
    ShopItemDescriptionToJSON,
} from './ShopItemDescription';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataShopItemDescription
 */
export interface NoSqlPagingListDataShopItemDescription {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataShopItemDescription
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataShopItemDescription
     */
    msg: string;
    /**
     * 
     * @type {Array<ShopItemDescription>}
     * @memberof NoSqlPagingListDataShopItemDescription
     */
    records?: Array<ShopItemDescription>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataShopItemDescription
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataShopItemDescription
     */
    pageState?: string;
}

export function NoSqlPagingListDataShopItemDescriptionFromJSON(json: any): NoSqlPagingListDataShopItemDescription {
    return NoSqlPagingListDataShopItemDescriptionFromJSONTyped(json, false);
}

export function NoSqlPagingListDataShopItemDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataShopItemDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(ShopItemDescriptionFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataShopItemDescriptionToJSON(value?: NoSqlPagingListDataShopItemDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(ShopItemDescriptionToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

