/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ASearchStore,
    ASearchStoreFromJSON,
    ASearchStoreFromJSONTyped,
    ASearchStoreToJSON,
} from './ASearchStore';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataASearchStore
 */
export interface NoSqlPagingListDataASearchStore {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataASearchStore
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataASearchStore
     */
    msg: string;
    /**
     * 
     * @type {Array<ASearchStore>}
     * @memberof NoSqlPagingListDataASearchStore
     */
    records?: Array<ASearchStore>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataASearchStore
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataASearchStore
     */
    pageState?: string;
}

export function NoSqlPagingListDataASearchStoreFromJSON(json: any): NoSqlPagingListDataASearchStore {
    return NoSqlPagingListDataASearchStoreFromJSONTyped(json, false);
}

export function NoSqlPagingListDataASearchStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataASearchStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(ASearchStoreFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataASearchStoreToJSON(value?: NoSqlPagingListDataASearchStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(ASearchStoreToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

