/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    VipShopGroupItem,
    VipShopGroupItemFromJSON,
    VipShopGroupItemFromJSONTyped,
    VipShopGroupItemToJSON,
} from './VipShopGroupItem';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataVipShopGroupItem
 */
export interface NoSqlPagingListDataVipShopGroupItem {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataVipShopGroupItem
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataVipShopGroupItem
     */
    msg: string;
    /**
     * 
     * @type {Array<VipShopGroupItem>}
     * @memberof NoSqlPagingListDataVipShopGroupItem
     */
    records?: Array<VipShopGroupItem>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataVipShopGroupItem
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataVipShopGroupItem
     */
    pageState?: string;
}

export function NoSqlPagingListDataVipShopGroupItemFromJSON(json: any): NoSqlPagingListDataVipShopGroupItem {
    return NoSqlPagingListDataVipShopGroupItemFromJSONTyped(json, false);
}

export function NoSqlPagingListDataVipShopGroupItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataVipShopGroupItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(VipShopGroupItemFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataVipShopGroupItemToJSON(value?: NoSqlPagingListDataVipShopGroupItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(VipShopGroupItemToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

