/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    LqUser,
    LqUserFromJSON,
    LqUserFromJSONTyped,
    LqUserToJSON,
} from './LqUser';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataLqUser
 */
export interface NoSqlPagingListDataLqUser {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataLqUser
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataLqUser
     */
    msg: string;
    /**
     * 
     * @type {Array<LqUser>}
     * @memberof NoSqlPagingListDataLqUser
     */
    records?: Array<LqUser>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataLqUser
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataLqUser
     */
    pageState?: string;
}

export function NoSqlPagingListDataLqUserFromJSON(json: any): NoSqlPagingListDataLqUser {
    return NoSqlPagingListDataLqUserFromJSONTyped(json, false);
}

export function NoSqlPagingListDataLqUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataLqUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(LqUserFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataLqUserToJSON(value?: NoSqlPagingListDataLqUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(LqUserToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

