/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    ShandianBrandItem,
    ShandianBrandItemFromJSON,
    ShandianBrandItemFromJSONTyped,
    ShandianBrandItemToJSON,
} from './ShandianBrandItem';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataShandianBrandItem
 */
export interface NoSqlPagingListDataShandianBrandItem {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataShandianBrandItem
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataShandianBrandItem
     */
    msg: string;
    /**
     * 
     * @type {Array<ShandianBrandItem>}
     * @memberof NoSqlPagingListDataShandianBrandItem
     */
    records?: Array<ShandianBrandItem>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataShandianBrandItem
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataShandianBrandItem
     */
    pageState?: string;
}

export function NoSqlPagingListDataShandianBrandItemFromJSON(json: any): NoSqlPagingListDataShandianBrandItem {
    return NoSqlPagingListDataShandianBrandItemFromJSONTyped(json, false);
}

export function NoSqlPagingListDataShandianBrandItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataShandianBrandItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(ShandianBrandItemFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataShandianBrandItemToJSON(value?: NoSqlPagingListDataShandianBrandItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(ShandianBrandItemToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

