/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    KunUser,
    KunUserFromJSON,
    KunUserFromJSONTyped,
    KunUserToJSON,
} from './KunUser';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataKunUser
 */
export interface NoSqlPagingListDataKunUser {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataKunUser
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataKunUser
     */
    msg: string;
    /**
     * 
     * @type {Array<KunUser>}
     * @memberof NoSqlPagingListDataKunUser
     */
    records?: Array<KunUser>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataKunUser
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataKunUser
     */
    pageState?: string;
}

export function NoSqlPagingListDataKunUserFromJSON(json: any): NoSqlPagingListDataKunUser {
    return NoSqlPagingListDataKunUserFromJSONTyped(json, false);
}

export function NoSqlPagingListDataKunUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataKunUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(KunUserFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataKunUserToJSON(value?: NoSqlPagingListDataKunUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(KunUserToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

