/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    KunSimpleOrder,
    KunSimpleOrderFromJSON,
    KunSimpleOrderFromJSONTyped,
    KunSimpleOrderToJSON,
} from './KunSimpleOrder';

/**
 * 
 * @export
 * @interface NoSqlPagingListDataKunSimpleOrder
 */
export interface NoSqlPagingListDataKunSimpleOrder {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof NoSqlPagingListDataKunSimpleOrder
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataKunSimpleOrder
     */
    msg: string;
    /**
     * 
     * @type {Array<KunSimpleOrder>}
     * @memberof NoSqlPagingListDataKunSimpleOrder
     */
    records?: Array<KunSimpleOrder>;
    /**
     * 
     * @type {number}
     * @memberof NoSqlPagingListDataKunSimpleOrder
     */
    pageSize: number;
    /**
     * 
     * @type {string}
     * @memberof NoSqlPagingListDataKunSimpleOrder
     */
    pageState?: string;
}

export function NoSqlPagingListDataKunSimpleOrderFromJSON(json: any): NoSqlPagingListDataKunSimpleOrder {
    return NoSqlPagingListDataKunSimpleOrderFromJSONTyped(json, false);
}

export function NoSqlPagingListDataKunSimpleOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSqlPagingListDataKunSimpleOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(KunSimpleOrderFromJSON)),
        'pageSize': json['pageSize'],
        'pageState': !exists(json, 'pageState') ? undefined : json['pageState'],
    };
}

export function NoSqlPagingListDataKunSimpleOrderToJSON(value?: NoSqlPagingListDataKunSimpleOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(KunSimpleOrderToJSON)),
        'pageSize': value.pageSize,
        'pageState': value.pageState,
    };
}

