/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    RetMiniAppUserItem,
    RetMiniAppUserItemFromJSON,
    RetMiniAppUserItemFromJSONTyped,
    RetMiniAppUserItemToJSON,
} from './RetMiniAppUserItem';

/**
 * 
 * @export
 * @interface OptionDataRetMiniAppUserItem
 */
export interface OptionDataRetMiniAppUserItem {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof OptionDataRetMiniAppUserItem
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof OptionDataRetMiniAppUserItem
     */
    msg: string;
    /**
     * 
     * @type {RetMiniAppUserItem}
     * @memberof OptionDataRetMiniAppUserItem
     */
    record?: RetMiniAppUserItem;
}

export function OptionDataRetMiniAppUserItemFromJSON(json: any): OptionDataRetMiniAppUserItem {
    return OptionDataRetMiniAppUserItemFromJSONTyped(json, false);
}

export function OptionDataRetMiniAppUserItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionDataRetMiniAppUserItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'record': !exists(json, 'record') ? undefined : RetMiniAppUserItemFromJSON(json['record']),
    };
}

export function OptionDataRetMiniAppUserItemToJSON(value?: OptionDataRetMiniAppUserItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'record': RetMiniAppUserItemToJSON(value.record),
    };
}

