/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    KunSimpleOrder,
    KunSimpleOrderFromJSON,
    KunSimpleOrderFromJSONTyped,
    KunSimpleOrderToJSON,
} from './KunSimpleOrder';

/**
 * 
 * @export
 * @interface OptionDataKunSimpleOrder
 */
export interface OptionDataKunSimpleOrder {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof OptionDataKunSimpleOrder
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof OptionDataKunSimpleOrder
     */
    msg: string;
    /**
     * 
     * @type {KunSimpleOrder}
     * @memberof OptionDataKunSimpleOrder
     */
    record?: KunSimpleOrder;
}

export function OptionDataKunSimpleOrderFromJSON(json: any): OptionDataKunSimpleOrder {
    return OptionDataKunSimpleOrderFromJSONTyped(json, false);
}

export function OptionDataKunSimpleOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionDataKunSimpleOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'record': !exists(json, 'record') ? undefined : KunSimpleOrderFromJSON(json['record']),
    };
}

export function OptionDataKunSimpleOrderToJSON(value?: OptionDataKunSimpleOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'record': KunSimpleOrderToJSON(value.record),
    };
}

