/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    DetailRootInterface,
    DetailRootInterfaceFromJSON,
    DetailRootInterfaceFromJSONTyped,
    DetailRootInterfaceToJSON,
} from './DetailRootInterface';

/**
 * 
 * @export
 * @interface OptionDataDetailRootInterface
 */
export interface OptionDataDetailRootInterface {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof OptionDataDetailRootInterface
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof OptionDataDetailRootInterface
     */
    msg: string;
    /**
     * 
     * @type {DetailRootInterface}
     * @memberof OptionDataDetailRootInterface
     */
    record?: DetailRootInterface;
}

export function OptionDataDetailRootInterfaceFromJSON(json: any): OptionDataDetailRootInterface {
    return OptionDataDetailRootInterfaceFromJSONTyped(json, false);
}

export function OptionDataDetailRootInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionDataDetailRootInterface {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'record': !exists(json, 'record') ? undefined : DetailRootInterfaceFromJSON(json['record']),
    };
}

export function OptionDataDetailRootInterfaceToJSON(value?: OptionDataDetailRootInterface | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'record': DetailRootInterfaceToJSON(value.record),
    };
}

