/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstantMSG,
    ConstantMSGFromJSON,
    ConstantMSGFromJSONTyped,
    ConstantMSGToJSON,
} from './ConstantMSG';
import {
    KunBenefitCard,
    KunBenefitCardFromJSON,
    KunBenefitCardFromJSONTyped,
    KunBenefitCardToJSON,
} from './KunBenefitCard';

/**
 * 
 * @export
 * @interface OptionDataKunBenefitCard
 */
export interface OptionDataKunBenefitCard {
    /**
     * 
     * @type {ConstantMSG}
     * @memberof OptionDataKunBenefitCard
     */
    code: ConstantMSG;
    /**
     * 
     * @type {string}
     * @memberof OptionDataKunBenefitCard
     */
    msg: string;
    /**
     * 
     * @type {KunBenefitCard}
     * @memberof OptionDataKunBenefitCard
     */
    record?: KunBenefitCard;
}

export function OptionDataKunBenefitCardFromJSON(json: any): OptionDataKunBenefitCard {
    return OptionDataKunBenefitCardFromJSONTyped(json, false);
}

export function OptionDataKunBenefitCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionDataKunBenefitCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': ConstantMSGFromJSON(json['code']),
        'msg': json['msg'],
        'record': !exists(json, 'record') ? undefined : KunBenefitCardFromJSON(json['record']),
    };
}

export function OptionDataKunBenefitCardToJSON(value?: OptionDataKunBenefitCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': ConstantMSGToJSON(value.code),
        'msg': value.msg,
        'record': KunBenefitCardToJSON(value.record),
    };
}

