/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqCreateConcern
 */
export interface ReqCreateConcern {
    /**
     * 
     * @type {boolean}
     * @memberof ReqCreateConcern
     */
    isUUID: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReqCreateConcern
     */
    target: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReqCreateConcern
     */
    isLinked: boolean;
}

export function ReqCreateConcernFromJSON(json: any): ReqCreateConcern {
    return ReqCreateConcernFromJSONTyped(json, false);
}

export function ReqCreateConcernFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqCreateConcern {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isUUID': json['isUUID'],
        'target': json['target'],
        'isLinked': json['isLinked'],
    };
}

export function ReqCreateConcernToJSON(value?: ReqCreateConcern | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isUUID': value.isUUID,
        'target': value.target,
        'isLinked': value.isLinked,
    };
}

