/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetExerciseItem
 */
export interface ReqGetExerciseItem {
    /**
     * 
     * @type {string}
     * @memberof ReqGetExerciseItem
     */
    exerciseId: string;
    /**
     * 
     * @type {string}
     * @memberof ReqGetExerciseItem
     */
    seriesId: string;
    /**
     * 
     * @type {string}
     * @memberof ReqGetExerciseItem
     */
    postId: string;
}

export function ReqGetExerciseItemFromJSON(json: any): ReqGetExerciseItem {
    return ReqGetExerciseItemFromJSONTyped(json, false);
}

export function ReqGetExerciseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetExerciseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exerciseId': json['exerciseId'],
        'seriesId': json['seriesId'],
        'postId': json['postId'],
    };
}

export function ReqGetExerciseItemToJSON(value?: ReqGetExerciseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exerciseId': value.exerciseId,
        'seriesId': value.seriesId,
        'postId': value.postId,
    };
}

