/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    HashLong,
    HashLongFromJSON,
    HashLongFromJSONTyped,
    HashLongToJSON,
} from './HashLong';

/**
 * 
 * @export
 * @interface ReqGetAudioLog
 */
export interface ReqGetAudioLog {
    /**
     * 
     * @type {HashLong}
     * @memberof ReqGetAudioLog
     */
    feedId: HashLong;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAudioLog
     */
    offset: number;
}

export function ReqGetAudioLogFromJSON(json: any): ReqGetAudioLog {
    return ReqGetAudioLogFromJSONTyped(json, false);
}

export function ReqGetAudioLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAudioLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feedId': HashLongFromJSON(json['feedId']),
        'offset': json['offset'],
    };
}

export function ReqGetAudioLogToJSON(value?: ReqGetAudioLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feedId': HashLongToJSON(value.feedId),
        'offset': value.offset,
    };
}

