/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqUpdateAudioLog
 */
export interface ReqUpdateAudioLog {
    /**
     * 
     * @type {string}
     * @memberof ReqUpdateAudioLog
     */
    feedId: string;
    /**
     * 
     * @type {number}
     * @memberof ReqUpdateAudioLog
     */
    offset: number;
}

export function ReqUpdateAudioLogFromJSON(json: any): ReqUpdateAudioLog {
    return ReqUpdateAudioLogFromJSONTyped(json, false);
}

export function ReqUpdateAudioLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqUpdateAudioLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feedId': json['feedId'],
        'offset': json['offset'],
    };
}

export function ReqUpdateAudioLogToJSON(value?: ReqUpdateAudioLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feedId': value.feedId,
        'offset': value.offset,
    };
}

