/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetccessTokenApp
 */
export interface RetccessTokenApp {
    /**
     * 
     * @type {string}
     * @memberof RetccessTokenApp
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof RetccessTokenApp
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof RetccessTokenApp
     */
    sign: string;
    /**
     * 
     * @type {string}
     * @memberof RetccessTokenApp
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof RetccessTokenApp
     */
    radon: string;
}

export function RetccessTokenAppFromJSON(json: any): RetccessTokenApp {
    return RetccessTokenAppFromJSONTyped(json, false);
}

export function RetccessTokenAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetccessTokenApp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'timestamp': json['timestamp'],
        'sign': json['sign'],
        'appId': json['appId'],
        'radon': json['radon'],
    };
}

export function RetccessTokenAppToJSON(value?: RetccessTokenApp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'timestamp': value.timestamp,
        'sign': value.sign,
        'appId': value.appId,
        'radon': value.radon,
    };
}

