/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetMiniAppUserItem
 */
export interface RetMiniAppUserItem {
    /**
     * 
     * @type {string}
     * @memberof RetMiniAppUserItem
     */
    openId: string;
    /**
     * 
     * @type {string}
     * @memberof RetMiniAppUserItem
     */
    nickName: string;
    /**
     * 
     * @type {string}
     * @memberof RetMiniAppUserItem
     */
    avatarUrl: string;
}

export function RetMiniAppUserItemFromJSON(json: any): RetMiniAppUserItem {
    return RetMiniAppUserItemFromJSONTyped(json, false);
}

export function RetMiniAppUserItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetMiniAppUserItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'openId': json['openId'],
        'nickName': json['nickName'],
        'avatarUrl': json['avatarUrl'],
    };
}

export function RetMiniAppUserItemToJSON(value?: RetMiniAppUserItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'openId': value.openId,
        'nickName': value.nickName,
        'avatarUrl': value.avatarUrl,
    };
}

