/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StarbuckStoreNameItem
 */
export interface StarbuckStoreNameItem {
    /**
     * 
     * @type {number}
     * @memberof StarbuckStoreNameItem
     */
    cityCode: number;
    /**
     * 
     * @type {number}
     * @memberof StarbuckStoreNameItem
     */
    storeId: number;
    /**
     * 
     * @type {string}
     * @memberof StarbuckStoreNameItem
     */
    storeName: string;
    /**
     * 
     * @type {string}
     * @memberof StarbuckStoreNameItem
     */
    storeAddress: string;
}

export function StarbuckStoreNameItemFromJSON(json: any): StarbuckStoreNameItem {
    return StarbuckStoreNameItemFromJSONTyped(json, false);
}

export function StarbuckStoreNameItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarbuckStoreNameItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cityCode': json['cityCode'],
        'storeId': json['storeId'],
        'storeName': json['storeName'],
        'storeAddress': json['storeAddress'],
    };
}

export function StarbuckStoreNameItemToJSON(value?: StarbuckStoreNameItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cityCode': value.cityCode,
        'storeId': value.storeId,
        'storeName': value.storeName,
        'storeAddress': value.storeAddress,
    };
}

