/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StarbuckAddress,
    StarbuckAddressFromJSON,
    StarbuckAddressFromJSONTyped,
    StarbuckAddressToJSON,
} from './StarbuckAddress';
import {
    StarbuckDetailOpenDetail,
    StarbuckDetailOpenDetailFromJSON,
    StarbuckDetailOpenDetailFromJSONTyped,
    StarbuckDetailOpenDetailToJSON,
} from './StarbuckDetailOpenDetail';
import {
    StarbuckLocation,
    StarbuckLocationFromJSON,
    StarbuckLocationFromJSONTyped,
    StarbuckLocationToJSON,
} from './StarbuckLocation';

/**
 * 
 * @export
 * @interface StarbuckDetailItem
 */
export interface StarbuckDetailItem {
    /**
     * 
     * @type {string}
     * @memberof StarbuckDetailItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StarbuckDetailItem
     */
    phoneNumber?: string;
    /**
     * 
     * @type {StarbuckDetailOpenDetail}
     * @memberof StarbuckDetailItem
     */
    today: StarbuckDetailOpenDetail;
    /**
     * 
     * @type {StarbuckAddress}
     * @memberof StarbuckDetailItem
     */
    address: StarbuckAddress;
    /**
     * 
     * @type {StarbuckLocation}
     * @memberof StarbuckDetailItem
     */
    coordinates: StarbuckLocation;
    /**
     * 
     * @type {string}
     * @memberof StarbuckDetailItem
     */
    storeNumber: string;
}

export function StarbuckDetailItemFromJSON(json: any): StarbuckDetailItem {
    return StarbuckDetailItemFromJSONTyped(json, false);
}

export function StarbuckDetailItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarbuckDetailItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'today': StarbuckDetailOpenDetailFromJSON(json['today']),
        'address': StarbuckAddressFromJSON(json['address']),
        'coordinates': StarbuckLocationFromJSON(json['coordinates']),
        'storeNumber': json['storeNumber'],
    };
}

export function StarbuckDetailItemToJSON(value?: StarbuckDetailItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'phoneNumber': value.phoneNumber,
        'today': StarbuckDetailOpenDetailToJSON(value.today),
        'address': StarbuckAddressToJSON(value.address),
        'coordinates': StarbuckLocationToJSON(value.coordinates),
        'storeNumber': value.storeNumber,
    };
}

