/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StarbuckLocation
 */
export interface StarbuckLocation {
    /**
     * 
     * @type {number}
     * @memberof StarbuckLocation
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof StarbuckLocation
     */
    latitude: number;
}

export function StarbuckLocationFromJSON(json: any): StarbuckLocation {
    return StarbuckLocationFromJSONTyped(json, false);
}

export function StarbuckLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarbuckLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'longitude': json['longitude'],
        'latitude': json['latitude'],
    };
}

export function StarbuckLocationToJSON(value?: StarbuckLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'longitude': value.longitude,
        'latitude': value.latitude,
    };
}

