/* tslint:disable */
/* eslint-disable */
/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VipShopWechatPaymentItem
 */
export interface VipShopWechatPaymentItem {
    /**
     * 
     * @type {number}
     * @memberof VipShopWechatPaymentItem
     */
    timeStamp: number;
    /**
     * 
     * @type {string}
     * @memberof VipShopWechatPaymentItem
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof VipShopWechatPaymentItem
     */
    nonceStr: string;
    /**
     * 
     * @type {string}
     * @memberof VipShopWechatPaymentItem
     */
    _package: string;
    /**
     * 
     * @type {string}
     * @memberof VipShopWechatPaymentItem
     */
    paySign: string;
    /**
     * 
     * @type {string}
     * @memberof VipShopWechatPaymentItem
     */
    signType: string;
    /**
     * 
     * @type {string}
     * @memberof VipShopWechatPaymentItem
     */
    orderId: string;
}

export function VipShopWechatPaymentItemFromJSON(json: any): VipShopWechatPaymentItem {
    return VipShopWechatPaymentItemFromJSONTyped(json, false);
}

export function VipShopWechatPaymentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): VipShopWechatPaymentItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeStamp': json['timeStamp'],
        'appId': json['appId'],
        'nonceStr': json['nonceStr'],
        '_package': json['package'],
        'paySign': json['paySign'],
        'signType': json['signType'],
        'orderId': json['orderId'],
    };
}

export function VipShopWechatPaymentItemToJSON(value?: VipShopWechatPaymentItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeStamp': value.timeStamp,
        'appId': value.appId,
        'nonceStr': value.nonceStr,
        'package': value._package,
        'paySign': value.paySign,
        'signType': value.signType,
        'orderId': value.orderId,
    };
}

