// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/
// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export type  ConstantMSG = string

export function isConstantMSG(v: any): boolean {
  console.error(v);
  return true
}

