// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { HorseCardReturn, isHorseCardReturn } from './HorseCardReturn';
import { HorseSeriesWithMeta, isHorseSeriesWithMeta } from './HorseSeriesWithMeta';
import { KunAppraiseRet } from './KunAppraiseRet';
import { KunProfile, isKunProfile } from './KunProfile';
import { NoSqlPagingListData } from './NoSqlPagingListData';

export interface HorseSeriesFull {
  series: HorseSeriesWithMeta;
  authorProfile: KunProfile;
  cards: ReadonlyArray<HorseCardReturn>;
  comments: NoSqlPagingListData<KunAppraiseRet>;
}

export function isHorseSeriesFull(v: any): v is HorseSeriesFull {
  return (
    (v['comments'] ) &&
    (Array.isArray(v['cards']) && v['cards'].every(elmt => elmt && isHorseCardReturn(elmt))) &&
    (v['authorProfile'] && isKunProfile(v['authorProfile'])) &&
    (v['series'] && isHorseSeriesWithMeta(v['series']))
  );
}
