// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const IMAGEInhabitant = "IMAGE";

export type IMAGE = typeof IMAGEInhabitant;





export function isIMAGE(v: any): v is IMAGE {
    return IMAGEInhabitant == v;
}

