// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const IMAGE_WITH_TEXTInhabitant = "IMAGE_WITH_TEXT";

export type IMAGE_WITH_TEXT = typeof IMAGE_WITH_TEXTInhabitant;

export function isIMAGE_WITH_TEXT(v: any): v is IMAGE_WITH_TEXT {
    return IMAGE_WITH_TEXTInhabitant == v;
}


