// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { ChildKunCommentReturn } from './ChildKunCommentReturn';
import { ConstantCommentType, isConstantCommentType } from './ConstantCommentType';
import { ConstantCommentUserType, isConstantCommentUserType } from './ConstantCommentUserType';
import { DateTime, isDateTime } from './DateTime';
import { HashLong, isHashLong } from './HashLong';
import { NoSqlPagingListData, isNoSqlPagingListData } from './NoSqlPagingListData';

export interface KunCommentWithDateHashLong {
  postId: HashLong;
  channelId: number;
  commentId: string;
  createAt: DateTime;
  content: string;
  commentUserId: string;
  commentUserName: string;
  commentUserAvatarOpt?: string;
  images?: ReadonlyArray<string>;
  commentType: ConstantCommentType;
  childCommentCount?: number;
  commentUserType?: ConstantCommentUserType;
  childComments: NoSqlPagingListData<ChildKunCommentReturn>;
}

export function isKunCommentWithDateHashLong(v: any): v is KunCommentWithDateHashLong {
  return (
    (v['childComments'] && isNoSqlPagingListData(v['childComments'])) &&
    (!v['commentUserType'] || (v['commentUserType'] && isConstantCommentUserType(v['commentUserType']))) &&
    (!v['childCommentCount'] || ((typeof v['childCommentCount']) === 'number')) &&
    (v['commentType'] && isConstantCommentType(v['commentType'])) &&
    (!v['images'] || (Array.isArray(v['images']) && v['images'].every(elmt => (typeof elmt) === 'string'))) &&
    (!v['commentUserAvatarOpt'] || ((typeof v['commentUserAvatarOpt']) === 'string')) &&
    ((typeof v['commentUserName']) === 'string') &&
    ((typeof v['commentUserId']) === 'string') &&
    ((typeof v['content']) === 'string') &&
    (v['createAt'] && isDateTime(v['createAt'])) &&
    ((typeof v['commentId']) === 'string') &&
    ((typeof v['channelId']) === 'number') &&
    (v['postId'] && isHashLong(v['postId']))
  );
}
