// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { ConstantMSG } from './ConstantMSG';

export interface NextPagingDataListById<T> {
  code: ConstantMSG;
  records: ReadonlyArray<T>;
  nextId?: number;
}
