// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { ConstantMSG } from './ConstantMSG';

export interface NoSqlPagingListData<T> {
  code: ConstantMSG;
  msg: string;
  records: ReadonlyArray<T>;
  pageState?: string;
}

export  function isNoSqlPagingListData (v: any) {
  console.log('v', v);
  return true;
}

