// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { ConstantMSG } from './ConstantMSG';
import { DateTime } from './DateTime';

export interface NoSqlPagingListDataPageMarkDateTime<T> {
  code: ConstantMSG;
  msg: string;
  records: ReadonlyArray<T>;
  pageState?: DateTime;
  prevPageMark?: DateTime;
}

