// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

import { ConstantMSG } from './ConstantMSG';

export interface PagingListData<T> {
  code: ConstantMSG;
  msg: string;
  records: ReadonlyArray<T>;
}
