// Generated by ScalaTS 0.5.7: https://scala-ts.github.io/scala-ts/

export const TXTInhabitant = "TXT";

export type TXT = typeof TXTInhabitant;

export function isTXT(v: any): v is TXT {
    return TXTInhabitant == v;
}

